import type { ScenarioDefinition } from "../../simulation";

const percentDomain = { min: 0, max: 1, clamp: true } as const;

const expansionGroups = [
  {
    id: "stable-expansion",
    title: "Sustainable mission and institutional stability",
    allOf: [
      {
        kind: "node-value",
        nodeId: "mission-reach",
        comparison: "at-least",
        value: 0.7,
      },
      {
        kind: "node-value",
        nodeId: "financial-stability",
        comparison: "at-least",
        value: 0.6,
      },
      {
        kind: "node-value",
        nodeId: "congregational-cohesion",
        comparison: "at-least",
        value: 0.65,
      },
    ],
  },
] as const;

export const exampleScenario = {
  id: "connectional-fellowship-1980",
  title: "The Connectional Fellowship",
  description:
    "Guide a growing fellowship through competing demands for institutional strength, local trust, ministry investment, and sustainable mission.",
  schemaVersion: 3,
  historicalActors: [
    {
      id: "central-office",
      name: "Central church office",
      role: "Institutional coordination",
      description:
        "Leaders coordinating the fellowship’s common ministries and commitments.",
    },
    {
      id: "regional-delegates",
      name: "Regional delegates",
      role: "Local representation",
      description:
        "Delegates bringing congregational concerns to the General Assembly.",
    },
    {
      id: "seminary-faculty",
      name: "Seminary faculty",
      role: "Clergy formation",
      description:
        "Teachers preparing clergy and debating the fellowship’s teaching traditions.",
    },
  ],
  completion: {
    prerequisiteGroups: [
      {
        id: "millennium-review",
        allOf: [{ kind: "turn", atTurn: 20 }],
        title: "The 2000 institutional review",
        description:
          "The fellowship reviews two decades of institutional leadership.",
      },
      {
        id: "sustainable-expansion",
        title: "Sustainable expansion achieved",
        description:
          "Mission reach, financial stability, and congregational cohesion support a durable expansion.",
        allOf: expansionGroups[0].allOf,
      },
    ],
    endings: [
      {
        id: "expansion",
        title: "Expansion",
        priority: 30,
        prerequisiteGroups: expansionGroups,
        narrative:
          "The fellowship extends its mission while preserving the finances and connections that sustain it. New communities join an institution capable of supporting their shared work.",
      },
      {
        id: "revival",
        title: "Revival",
        priority: 20,
        prerequisiteGroups: [
          {
            id: "renewed-participation",
            title: "Renewed worship and membership",
            allOf: [
              {
                kind: "node-value",
                nodeId: "worship-participation",
                comparison: "at-least",
                value: 0.65,
              },
              {
                kind: "node-value",
                nodeId: "member-retention",
                comparison: "at-least",
                value: 0.65,
              },
            ],
          },
        ],
        narrative:
          "Renewed worship and lasting congregational connections give the fellowship fresh vitality. Its institutional legacy lives in communities that continue to gather and serve.",
      },
      {
        id: "preservation",
        title: "Preservation",
        priority: 10,
        prerequisiteGroups: [
          {
            id: "institution-preserved",
            title: "A connected and viable institution",
            allOf: [
              {
                kind: "node-value",
                nodeId: "congregational-cohesion",
                comparison: "at-least",
                value: 0.55,
              },
              {
                kind: "node-value",
                nodeId: "financial-stability",
                comparison: "at-least",
                value: 0.5,
              },
            ],
          },
        ],
        narrative:
          "The fellowship remains connected and financially viable. Its ministries continue, carrying inherited commitments into a new period of leadership.",
      },
    ],
    fallbackEnding: {
      id: "unresolved-crisis",
      title: "Unresolved Crisis",
      narrative:
        "The review closes with the fellowship still standing, but without a settled institutional direction. Its unresolved tensions and commitments pass to those who follow.",
    },
    reportNodeIds: [
      "mission-reach",
      "financial-stability",
      "congregational-cohesion",
      "worship-participation",
      "member-retention",
      "money",
      "authority",
    ],
  },
  start: { turn: 0, year: 1980 },
  conditions: ["has-seminary", "has-general-assembly"],
  events: [
    {
      kind: "event",
      id: "regional-petition",
      title: "Regional delegates submit a petition",
      description:
        "Delegates ask the central office to hear local concerns before setting another common course.",
      influences: [{ source: "centralization", coefficient: 1 }],
      threshold: 0.5,
      cooldownTurns: 3,
      requires: ["has-general-assembly"],
      consequences: [
        { kind: "resource", target: "authority", amount: -2 },
        {
          kind: "grudge",
          target: "leadership-trust",
          magnitude: -0.02,
          decay: 0.75,
          label: "Unanswered regional petition",
        },
      ],
    },
    {
      kind: "event",
      id: "unexpected-bequest",
      title: "An unexpected bequest arrives",
      description:
        "A longtime supporter leaves an unrestricted gift to sustain shared ministries.",
      influences: [{ source: "_random_", coefficient: 1 }],
      threshold: 0.6,
      cooldownTurns: 4,
      consequences: [{ kind: "resource", target: "money", amount: 4 }],
    },
  ],
  dilemmas: [
    {
      kind: "dilemma",
      id: "assembly-governance-dispute",
      title: "An Assembly dispute over local authority",
      description:
        "District delegates demand a response to mounting tension over central direction.",
      influences: [{ source: "governance-tension", coefficient: 1 }],
      threshold: 0.58,
      cooldownTurns: 3,
      requires: ["has-general-assembly"],
      choices: [
        {
          id: "convene-mediation",
          label: "Convene regional mediation",
          description:
            "Spend institutional authority to bring district leaders into a shared process.",
          consequences: [
            { kind: "resource", target: "authority", amount: -4 },
            {
              kind: "grudge",
              target: "leadership-trust",
              magnitude: 0.04,
              decay: 0.75,
              label: "Regional mediation",
            },
          ],
        },
        {
          id: "reassert-direction",
          label: "Reassert central direction",
          description:
            "Defend the office's mandate while risking deeper division.",
          consequences: [
            { kind: "resource", target: "authority", amount: 3 },
            {
              kind: "grudge",
              target: "congregational-cohesion",
              magnitude: -0.05,
              decay: 0.75,
              label: "Disputed central direction",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "christological-teaching-request",
      title: "A request for teaching on the nature of Christ",
      description:
        "Pastors ask for guidance after their congregations hear conflicting accounts of Christ's divinity and humanity.",
      influences: [{ source: "_random_", coefficient: 1 }],
      threshold: 0.72,
      cooldownTurns: 8,
      choices: [
        {
          id: "publish-confession",
          label: "Publish a common confession",
          description:
            "State the fellowship's teaching on Christ's full divinity and full humanity.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "clergy-quality",
              magnitude: 0.035,
              decay: 0.75,
              label: "Shared Christological teaching",
            },
          ],
        },
        {
          id: "host-study",
          label: "Host a theological study",
          description:
            "Invite clergy and congregations into a guided study before issuing guidance.",
          consequences: [
            { kind: "resource", target: "money", amount: -3 },
            {
              kind: "grudge",
              target: "leadership-trust",
              magnitude: 0.025,
              decay: 0.75,
              label: "Open theological study",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "seminary-christology-curriculum",
      title: "Seminary faculty debate the Christology curriculum",
      description:
        "Faculty disagree over how much time to give historical creeds and contemporary interpretation.",
      influences: [{ source: "clergy-formation", coefficient: 1 }],
      threshold: 0.35,
      cooldownTurns: 7,
      choices: [
        {
          id: "expand-creedal-study",
          label: "Expand study of the creeds",
          description:
            "Fund additional teaching on the early councils and their language about Christ.",
          consequences: [
            { kind: "resource", target: "money", amount: -3 },
            {
              kind: "grudge",
              target: "clergy-quality",
              magnitude: 0.035,
              decay: 0.8,
              label: "Expanded creedal study",
            },
          ],
        },
        {
          id: "support-local-dialogue",
          label: "Support local theological dialogue",
          description:
            "Give faculty room to develop material for questions arising in congregations.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "renewal-network-satisfaction",
              magnitude: 0.035,
              decay: 0.8,
              label: "Theological dialogue",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "pastoral-appointment-policy",
      title: "Districts seek a new appointment policy",
      description:
        "Rural congregations want longer pastoral appointments while the central office needs flexibility.",
      influences: [
        {
          source: "rural-congregations-satisfaction",
          coefficient: 1,
        },
      ],
      threshold: 0.35,
      cooldownTurns: 6,
      choices: [
        {
          id: "lengthen-appointments",
          label: "Lengthen appointments",
          description:
            "Give rural pastors more time to build local relationships.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "rural-congregations-satisfaction",
              magnitude: 0.04,
              decay: 0.75,
              label: "Stable rural appointments",
            },
          ],
        },
        {
          id: "keep-flexibility",
          label: "Keep flexible assignments",
          description:
            "Preserve the ability to send clergy where need is most urgent.",
          consequences: [
            { kind: "resource", target: "authority", amount: 2 },
            {
              kind: "grudge",
              target: "rural-congregations-satisfaction",
              magnitude: -0.035,
              decay: 0.75,
              label: "Unsettled appointment concerns",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "shared-worship-guidance",
      title: "Congregations request worship guidance",
      description:
        "Different local practices prompt a request for a common worship guide.",
      influences: [{ source: "worship-practice", coefficient: 1 }],
      threshold: 0.3,
      cooldownTurns: 6,
      choices: [
        {
          id: "publish-guide",
          label: "Publish a common guide",
          description:
            "Prepare shared resources while leaving room for local adaptation.",
          consequences: [
            { kind: "resource", target: "money", amount: -2 },
            {
              kind: "grudge",
              target: "worship-participation",
              magnitude: 0.03,
              decay: 0.75,
              label: "Common worship resources",
            },
          ],
        },
        {
          id: "leave-local",
          label: "Leave practice to congregations",
          description:
            "Let each congregation discern its own forms of worship.",
          consequences: [
            {
              kind: "grudge",
              target: "lay-leadership-satisfaction",
              magnitude: 0.03,
              decay: 0.75,
              label: "Local worship discretion",
            },
            {
              kind: "grudge",
              target: "traditionalist-coalition-satisfaction",
              magnitude: -0.02,
              decay: 0.75,
              label: "Unsettled worship guidance",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "relief-fund-policy",
      title: "A proposal for a shared relief fund",
      description:
        "Congregations ask for a common fund to meet sudden local hardship.",
      influences: [{ source: "_random_", coefficient: 1 }],
      threshold: 0.78,
      cooldownTurns: 8,
      choices: [
        {
          id: "create-fund",
          label: "Create the fund",
          description:
            "Set aside money for local relief and invite congregations to participate.",
          consequences: [
            { kind: "resource", target: "money", amount: -4 },
            {
              kind: "grudge",
              target: "charitable-impact",
              magnitude: 0.045,
              decay: 0.75,
              label: "Shared relief fund",
            },
          ],
        },
        {
          id: "coordinate-existing",
          label: "Coordinate existing ministries",
          description:
            "Ask districts to connect families with the help already available.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "lay-leadership-satisfaction",
              magnitude: 0.03,
              decay: 0.75,
              label: "Coordinated local relief",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "financial-reporting-policy",
      title: "Delegates call for clearer financial reports",
      description:
        "Local treasurers want to understand how shared contributions are spent.",
      influences: [{ source: "giving-strength", coefficient: 1 }],
      threshold: 0.3,
      cooldownTurns: 7,
      choices: [
        {
          id: "publish-accounts",
          label: "Publish detailed accounts",
          description:
            "Prepare a regular report that congregations can inspect.",
          consequences: [
            { kind: "resource", target: "money", amount: -2 },
            {
              kind: "grudge",
              target: "leadership-trust",
              magnitude: 0.035,
              decay: 0.8,
              label: "Open financial reporting",
            },
          ],
        },
        {
          id: "district-briefings",
          label: "Brief district leaders",
          description:
            "Explain spending in smaller meetings with local delegates.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "congregational-cohesion",
              magnitude: 0.025,
              decay: 0.75,
              label: "District financial briefings",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "youth-leadership-voice",
      title: "Young leaders ask for a voice",
      description:
        "Emerging leaders request a formal place in district planning.",
      influences: [{ source: "youth-engagement", coefficient: 1 }],
      threshold: 0.3,
      cooldownTurns: 6,
      choices: [
        {
          id: "seat-delegates",
          label: "Seat youth delegates",
          description:
            "Give young leaders voting representation in district councils.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "emerging-leaders-satisfaction",
              magnitude: 0.05,
              decay: 0.75,
              label: "Youth delegates seated",
            },
          ],
        },
        {
          id: "fund-mentoring",
          label: "Fund mentoring instead",
          description:
            "Build a training path before changing council membership.",
          consequences: [
            { kind: "resource", target: "money", amount: -3 },
            {
              kind: "grudge",
              target: "clergy-quality",
              magnitude: 0.025,
              decay: 0.75,
              label: "Youth mentoring",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "ecumenical-christology-forum",
      title: "An invitation to discuss Christ across traditions",
      description:
        "Nearby churches invite the fellowship to a public forum on their shared and differing claims about Christ.",
      influences: [{ source: "_random_", coefficient: 1 }],
      threshold: 0.82,
      cooldownTurns: 9,
      choices: [
        {
          id: "join-forum",
          label: "Join the forum",
          description:
            "Send theologians to explain the fellowship's convictions and hear its neighbors.",
          consequences: [
            { kind: "resource", target: "money", amount: -2 },
            {
              kind: "grudge",
              target: "newcomer-welcome",
              magnitude: 0.04,
              decay: 0.75,
              label: "Christology forum",
            },
          ],
        },
        {
          id: "hold-local-classes",
          label: "Hold local classes",
          description:
            "Focus on teaching the fellowship's own congregations first.",
          consequences: [
            { kind: "resource", target: "authority", amount: -1 },
            {
              kind: "grudge",
              target: "traditionalist-coalition-satisfaction",
              magnitude: 0.03,
              decay: 0.75,
              label: "Local doctrinal classes",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "volunteer-sabbath-policy",
      title: "Volunteers ask for a rest policy",
      description:
        "Ministry teams report that recurring duties leave little time for rest.",
      influences: [{ source: "volunteer-fatigue", coefficient: 1 }],
      threshold: 0.25,
      cooldownTurns: 6,
      choices: [
        {
          id: "rotate-duties",
          label: "Rotate duties",
          description:
            "Ask ministries to schedule rest and share responsibilities more widely.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "volunteer-health",
              magnitude: 0.04,
              decay: 0.75,
              label: "Volunteer rest rotation",
            },
          ],
        },
        {
          id: "fund-support",
          label: "Fund practical support",
          description:
            "Pay for temporary help so current volunteers can step back.",
          consequences: [
            { kind: "resource", target: "money", amount: -4 },
            {
              kind: "grudge",
              target: "ministry-capacity",
              magnitude: 0.035,
              decay: 0.75,
              label: "Volunteer support",
            },
          ],
        },
      ],
    },
    {
      kind: "dilemma",
      id: "digital-pastoral-care-policy",
      title: "A policy for online pastoral care",
      description:
        "Ministers seek guidance on confidential conversations conducted online.",
      influences: [{ source: "digital-ministry", coefficient: 1 }],
      threshold: 0.3,
      cooldownTurns: 7,
      choices: [
        {
          id: "train-pastors",
          label: "Train pastors",
          description:
            "Develop guidance and training for privacy and follow-up.",
          consequences: [
            { kind: "resource", target: "money", amount: -3 },
            {
              kind: "grudge",
              target: "clergy-quality",
              magnitude: 0.03,
              decay: 0.75,
              label: "Online care training",
            },
          ],
        },
        {
          id: "local-protocols",
          label: "Let districts set protocols",
          description:
            "Ask district leaders to set safeguards suited to local practice.",
          consequences: [
            { kind: "resource", target: "authority", amount: -2 },
            {
              kind: "grudge",
              target: "lay-leadership-satisfaction",
              magnitude: 0.03,
              decay: 0.75,
              label: "Local online care protocols",
            },
          ],
        },
      ],
    },
  ],
  gameOvers: [
    {
      id: "loss-of-connectional-mandate",
      title: "Loss of connectional mandate",
      prerequisiteGroups: [
        {
          id: "authority-and-trust-exhausted",
          title: "Authority and trust exhausted",
          allOf: [
            {
              kind: "node-value",
              nodeId: "institutional-authority",
              comparison: "at-most",
              value: 0.12,
            },
            {
              kind: "node-value",
              nodeId: "leadership-trust",
              comparison: "at-most",
              value: 0.2,
            },
          ],
        },
      ],
      terminalAfterTurns: 4,
      stages: [
        {
          id: "assembly-inquiry",
          atTurn: 1,
          title: "The Assembly opens an inquiry",
          description:
            "Regional leaders formally question whether the central office still carries a connectional mandate.",
          consequences: [{ kind: "resource", target: "authority", amount: -3 }],
        },
        {
          id: "formal-investigation",
          atTurn: 2,
          title: "A formal investigation begins",
          description:
            "The inquiry widens as records, appointments, and disputed decisions are brought before the Assembly.",
          consequences: [
            {
              kind: "grudge",
              target: "institutional-authority",
              magnitude: -0.04,
              decay: 0.75,
              label: "Assembly investigation",
            },
          ],
        },
        {
          id: "deposition-hearing",
          atTurn: 3,
          title: "A deposition hearing is called",
          description:
            "A rival slate asks the Assembly to withdraw recognition from the present leadership.",
          consequences: [
            { kind: "resource", target: "authority", amount: -5 },
            {
              kind: "grudge",
              target: "leadership-trust",
              magnitude: -0.05,
              decay: 0.75,
              label: "Public challenge to the leadership",
            },
          ],
        },
      ],
      recovery: {
        title: "The mandate is reaffirmed",
        description:
          "The Assembly's challenge recedes after confidence and practical authority are restored.",
        consequences: [
          { kind: "resource", target: "authority", amount: 4 },
          {
            kind: "grudge",
            target: "leadership-trust",
            magnitude: 0.03,
            decay: 0.5,
            label: "Reaffirmed mandate",
          },
        ],
      },
      report: {
        title: "The Assembly withdraws your mandate",
        narrative:
          "After years of exhausted authority and public distrust, the General Assembly recognizes new leadership. Your commission to guide the fellowship has ended.",
      },
    },
    {
      id: "denominational-fracture",
      title: "Denominational fracture",
      prerequisiteGroups: [
        {
          id: "tension-without-cohesion",
          title: "Governance fracture",
          allOf: [
            {
              kind: "node-activation",
              nodeId: "governance-tension",
              active: true,
            },
            {
              kind: "node-value",
              nodeId: "congregational-cohesion",
              comparison: "at-most",
              value: 0.3,
            },
          ],
        },
      ],
      terminalAfterTurns: 5,
      stages: [
        {
          id: "public-dissent",
          atTurn: 1,
          title: "Regional dissent becomes public",
          description:
            "Congregations begin openly disputing the fellowship's ability to hold its common life together.",
          consequences: [{ kind: "resource", target: "authority", amount: -2 }],
        },
        {
          id: "withheld-cooperation",
          atTurn: 2,
          title: "Congregations withhold cooperation",
          description:
            "Shared ministries falter as regional networks stop cooperating with central initiatives.",
          consequences: [
            {
              kind: "grudge",
              target: "congregational-cohesion",
              magnitude: -0.03,
              decay: 0.8,
              label: "Withheld regional cooperation",
            },
          ],
        },
        {
          id: "rival-organization",
          atTurn: 3,
          title: "A rival organization takes shape",
          description:
            "Dissenting districts establish their own council and begin speaking for the fellowship.",
          consequences: [{ kind: "resource", target: "authority", amount: -4 }],
        },
        {
          id: "separation-convention",
          atTurn: 4,
          title: "A separation convention is summoned",
          description:
            "Delegates gather to divide congregations, property, and ministries between competing bodies.",
          consequences: [
            {
              kind: "grudge",
              target: "congregational-cohesion",
              magnitude: -0.05,
              decay: 0.8,
              label: "Preparations for separation",
            },
          ],
        },
      ],
      recovery: {
        title: "The separation movement disperses",
        description:
          "Renewed cooperation deprives the rival council of the support needed to divide the fellowship.",
        consequences: [
          { kind: "resource", target: "authority", amount: 3 },
          {
            kind: "grudge",
            target: "congregational-cohesion",
            magnitude: 0.03,
            decay: 0.5,
            label: "Renewed connectional cooperation",
          },
        ],
      },
      report: {
        title: "The fellowship divides",
        narrative:
          "The separation convention creates rival regional fellowships. The connectional body you led no longer exists as a single institution.",
      },
    },
    {
      id: "institutional-insolvency",
      title: "Institutional insolvency",
      prerequisiteGroups: [
        {
          id: "strain-without-reserves",
          title: "Institutional financial crisis",
          allOf: [
            {
              kind: "node-activation",
              nodeId: "financial-strain",
              active: true,
            },
            {
              kind: "node-value",
              nodeId: "money",
              comparison: "at-most",
              value: 10,
            },
          ],
        },
        {
          id: "severe-debt",
          title: "Severe institutional debt",
          allOf: [
            {
              kind: "node-value",
              nodeId: "money",
              comparison: "at-most",
              value: -30,
            },
          ],
        },
      ],
      terminalAfterTurns: 3,
      stages: [
        {
          id: "emergency-restrictions",
          atTurn: 1,
          title: "Emergency restrictions are imposed",
          description:
            "The treasury suspends ordinary commitments to preserve its remaining cash.",
          consequences: [{ kind: "resource", target: "money", amount: -3 }],
        },
        {
          id: "creditor-intervention",
          atTurn: 2,
          title: "Creditors intervene",
          description:
            "External claims now determine which ministries can continue and which obligations go unpaid.",
          consequences: [
            { kind: "resource", target: "money", amount: -3 },
            {
              kind: "grudge",
              target: "financial-stability",
              magnitude: -0.05,
              decay: 0.75,
              label: "Creditor intervention",
            },
          ],
        },
      ],
      recovery: {
        title: "The emergency budget holds",
        description:
          "Restored reserves and operating stability allow the institution to resume control of its obligations.",
        consequences: [
          { kind: "resource", target: "money", amount: 4 },
          {
            kind: "grudge",
            target: "financial-stability",
            magnitude: 0.03,
            decay: 0.5,
            label: "Confidence in the emergency budget",
          },
        ],
      },
      report: {
        title: "The institution enters external administration",
        narrative:
          "With obligations unmet and reserves exhausted, trustees surrender control to an external administrator. Your leadership can no longer direct the fellowship's work.",
      },
    },
  ],
  factionMetrics: [
    { id: "satisfaction", label: "Satisfaction" },
    { id: "membership", label: "Membership" },
  ],
  factionGroups: [
    {
      id: "traditionalist-coalition",
      name: "Traditionalist Members",
      description: "Members who favor inherited doctrine and worship.",
      metrics: {
        satisfaction: "traditionalist-coalition-satisfaction",
        membership: "traditionalist-coalition-membership",
      },
    },
    {
      id: "renewal-network",
      name: "Renewal Members",
      description: "Members who favor experimentation and outreach.",
      metrics: {
        satisfaction: "renewal-network-satisfaction",
        membership: "renewal-network-membership",
      },
    },
    {
      id: "lay-leadership",
      name: "Lay Leadership",
      description: "Non-clergy members who lead local ministry.",
      metrics: {
        satisfaction: "lay-leadership-satisfaction",
        membership: "lay-leadership-membership",
      },
    },
    {
      id: "emerging-leaders",
      name: "Emerging Leaders",
      description: "Young clergy and lay leaders preparing for ministry.",
      metrics: {
        satisfaction: "emerging-leaders-satisfaction",
        membership: "emerging-leaders-membership",
      },
    },
    {
      id: "rural-congregations",
      name: "Rural Congregations",
      description: "Members of rural congregations.",
      metrics: {
        satisfaction: "rural-congregations-satisfaction",
        membership: "rural-congregations-membership",
      },
    },
    {
      id: "urban-missionaries",
      name: "Urban Missionaries",
      description: "Ministers and members serving urban communities.",
      metrics: {
        satisfaction: "urban-missionaries-satisfaction",
        membership: "urban-missionaries-membership",
      },
    },
    {
      id: "confessional-members",
      name: "Confessional Members",
      description: "Members with confessional convictions.",
      metrics: {
        satisfaction: "confessional-members-satisfaction",
        membership: "confessional-members-membership",
      },
    },
    {
      id: "ecumenical-members",
      name: "Ecumenical Members",
      description: "Members who support ecumenical ties.",
      metrics: {
        satisfaction: "ecumenical-members-satisfaction",
        membership: "ecumenical-members-membership",
      },
    },
    {
      id: "youth-members",
      name: "Youth Members",
      description: "Younger members.",
      metrics: {
        satisfaction: "youth-members-satisfaction",
        membership: "youth-members-membership",
      },
    },
    {
      id: "student-members",
      name: "Student Members",
      description: "Members in education.",
      metrics: {
        satisfaction: "student-members-satisfaction",
        membership: "student-members-membership",
      },
    },
    {
      id: "clergy-members",
      name: "Clergy",
      description: "Ordained clergy.",
      metrics: {
        satisfaction: "clergy-members-satisfaction",
        membership: "clergy-members-membership",
      },
    },
  ],
  constraints: [
    {
      id: "worship-continuity",
      name: "Worship continuity and renewal",
      kind: "sum-limit",
      maxTotal: 1,
    },
    {
      id: "confessional-boundaries",
      name: "Confessional boundaries and ecumenism",
      kind: "sum-limit",
      maxTotal: 1,
    },
  ],
  nodes: [
    {
      id: "centralization",
      type: "stance",
      name: "Centralization",
      description:
        "How much authority is concentrated in the central church office.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.55, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: {
        resourceId: "authority",
        base: 0.5,
        perPoint: 12,
      },
    },
    {
      id: "clergy-formation",
      type: "stance",
      name: "Clergy Formation",
      description:
        "The rigor and institutional investment required for clergy formation.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.6, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      requires: ["has-seminary"],
      cost: {
        resourceId: "authority",
        base: 0.5,
        perPoint: 10,
      },
    },
    {
      id: "governance-reach",
      type: "indicator",
      name: "Governance Reach",
      description:
        "The central institution’s ability to coordinate congregations.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.5325, isActive: true, isForced: true },
      baseline: 0.12,
    },
    {
      id: "leadership-trust",
      type: "indicator",
      name: "Leadership Trust",
      description: "Confidence in denominational leadership.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.436, isActive: true, isForced: true },
      baseline: 0.25,
    },
    {
      id: "congregational-cohesion",
      type: "indicator",
      name: "Congregational Cohesion",
      description:
        "The denomination’s ability to remain connected despite disagreement.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.646, isActive: true, isForced: true },
      baseline: 0.35,
    },
    {
      id: "clergy-quality",
      type: "indicator",
      name: "Clergy Quality",
      description: "The preparation and effectiveness of active clergy.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.57, isActive: true, isForced: true },
      baseline: 0.18,
    },
    {
      id: "localist-movement",
      type: "situation",
      name: "Local Autonomy Campaign",
      description:
        "An organized campaign for local autonomy grows from dissatisfied congregations and governance pressure.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.3, isActive: false, isForced: false },
      baseline: 0.15,
      startThreshold: 0.65,
      stopThreshold: 0.35,
    },
    {
      id: "institutional-authority",
      type: "indicator",
      name: "Institutional Authority",
      description:
        "The legitimacy and practical ability of denominational leaders to coordinate shared decisions.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.285, isActive: true, isForced: true },
      baseline: 0.1,
    },
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description:
        "Institutional latitude available for changing established Stances.",
      category: "Governance",
      domain: { min: 0, max: 100, clamp: true },
      initial: { value: 40, isActive: true, isForced: true },
      graphVisible: false,
    },
    {
      id: "money",
      type: "resource",
      name: "Money",
      description:
        "The accumulated treasury balance for shared ministry; negative values are debt.",
      category: "Finance and Assets",
      domain: { min: -100, max: 100, clamp: false },
      initial: { value: 40, isActive: true, isForced: true },
      graphVisible: false,
    },
    {
      id: "governance-tension",
      type: "situation",
      name: "Governance Tension",
      description:
        "Organized resistance to central direction has become persistent.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.41575, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.58,
      stopThreshold: 0.42,
    },
    {
      id: "clergy-shortage",
      type: "situation",
      name: "Clergy Shortage",
      description:
        "The available supply of well-prepared clergy is insufficient.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.3125, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.58,
      stopThreshold: 0.4,
    },
    {
      id: "worship-practice",
      type: "stance",
      name: "Worship Practice",
      description:
        "How strongly congregations emphasize shared worship and inherited forms of practice.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.52, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 7 },
    },
    {
      id: "charitable-commitment",
      type: "stance",
      name: "Charitable Commitment",
      description:
        "The share of institutional attention and funding devoted to care for neighbors in need.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.48, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "money", base: 0.5, perPoint: 8 },
    },
    {
      id: "missionary-outreach",
      type: "stance",
      name: "Missionary Outreach",
      description:
        "The denomination’s willingness to invest in ministry beyond its established congregations.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.42, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 9 },
    },
    {
      id: "financial-discipline",
      type: "stance",
      name: "Financial Discipline",
      description:
        "How firmly the denomination protects reserves and requires sustainable ministry budgets.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.58, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 6 },
    },
    {
      id: "worship-participation",
      type: "indicator",
      name: "Worship Participation",
      description:
        "The consistency with which members gather for shared worship and practice.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.56, isActive: true, isForced: true },
      baseline: 0.24,
    },
    {
      id: "member-retention",
      type: "indicator",
      name: "Member Retention",
      description:
        "The denomination’s ability to keep households connected across changing seasons.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.62, isActive: true, isForced: true },
      baseline: 0.26,
    },
    {
      id: "charitable-impact",
      type: "indicator",
      name: "Charitable Impact",
      description:
        "The practical reach and perceived effectiveness of the denomination’s care ministries.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.49, isActive: true, isForced: true },
      baseline: 0.15,
    },
    {
      id: "mission-reach",
      type: "indicator",
      name: "Mission Reach",
      description:
        "The denomination’s ability to form new communities and serve beyond its existing base.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.44, isActive: true, isForced: true },
      baseline: 0.12,
    },
    {
      id: "financial-stability",
      type: "indicator",
      name: "Financial Stability",
      description:
        "The institution’s ability to meet commitments while sustaining ministry over time.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.56, isActive: true, isForced: true },
      baseline: 0.18,
    },
    {
      id: "traditionalist-coalition-satisfaction",
      type: "faction",
      name: "Traditionalist Members — Satisfaction",
      description: "Members who favor inherited doctrine and worship.",
      category: "Worship and Practice",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.53,
        isActive: true,
        isForced: true,
      },
      baseline: 0.6,
    },
    {
      id: "traditionalist-coalition-membership",
      type: "faction",
      name: "Traditionalist Members — Membership",
      description: "Members who favor inherited doctrine and worship.",
      category: "Worship and Practice",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.4,
        isActive: true,
        isForced: true,
      },
      constraintId: "worship-continuity",
    },
    {
      id: "renewal-network-satisfaction",
      type: "faction",
      name: "Renewal Members — Satisfaction",
      description: "Members who favor experimentation and outreach.",
      category: "Mission and Expansion",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.47,
        isActive: true,
        isForced: true,
      },
      baseline: 0.32,
    },
    {
      id: "renewal-network-membership",
      type: "faction",
      name: "Renewal Members — Membership",
      description: "Members who favor experimentation and outreach.",
      category: "Mission and Expansion",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.35,
        isActive: true,
        isForced: true,
      },
      constraintId: "worship-continuity",
    },
    {
      id: "lay-leadership-satisfaction",
      type: "faction",
      name: "Lay Leadership — Satisfaction",
      description: "Non-clergy members who lead local ministry.",
      category: "Governance",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.5,
        isActive: true,
        isForced: true,
      },
      baseline: 0.4,
    },
    {
      id: "lay-leadership-membership",
      type: "faction",
      name: "Lay Leadership — Membership",
      description: "Non-clergy members who lead local ministry.",
      category: "Governance",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.2,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "membership-decline",
      type: "situation",
      name: "Membership Decline",
      description:
        "A persistent loss of connected households threatens the fellowship’s local presence.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.24, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.62,
      stopThreshold: 0.4,
    },
    {
      id: "financial-strain",
      type: "situation",
      name: "Financial Strain",
      description:
        "Operating commitments and weakened reserves are placing the ministry budget under pressure.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.22, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.4,
      stopThreshold: 0.28,
    },
    {
      id: "community-partnerships",
      type: "stance",
      name: "Community Partnerships",
      description:
        "How intentionally the denomination works with local civic, charitable, and ecumenical partners.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.46, isActive: false, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "money", base: 0.5, perPoint: 8 },
      enactmentCost: { resourceId: "authority", amount: 6 },
      repealCost: { resourceId: "authority", amount: 3 },
    },
    {
      id: "youth-formation",
      type: "stance",
      name: "Youth Formation",
      description:
        "The priority given to sustained discipleship, mentoring, and leadership opportunities for younger members.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.43, isActive: true, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 9 },
      enactmentCost: { resourceId: "authority", amount: 5 },
      repealCost: { resourceId: "authority", amount: 2 },
    },
    {
      id: "regional-vitality",
      type: "indicator",
      name: "Regional Vitality",
      description:
        "The health and momentum of congregations across the fellowship’s regions.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.51, isActive: true, isForced: true },
      baseline: 0.14,
    },
    {
      id: "youth-engagement",
      type: "indicator",
      name: "Youth Engagement",
      description:
        "The consistency with which younger members participate in worship, service, and formation.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.41, isActive: true, isForced: true },
      baseline: 0.1,
    },
    {
      id: "emerging-leaders-satisfaction",
      type: "faction",
      name: "Emerging Leaders — Satisfaction",
      description: "Young clergy and lay leaders preparing for ministry.",
      category: "Mission and Expansion",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.38,
        isActive: true,
        isForced: true,
      },
      baseline: 0.12,
    },
    {
      id: "emerging-leaders-membership",
      type: "faction",
      name: "Emerging Leaders — Membership",
      description: "Young clergy and lay leaders preparing for ministry.",
      category: "Mission and Expansion",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.1,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "ministry-capacity",
      type: "indicator",
      name: "Ministry Capacity",
      description:
        "Staff time, trained volunteers, and operational room available for new ministry commitments.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.43, isActive: true, isForced: true },
      baseline: 0.24,
    },
    {
      id: "regional-coordination",
      type: "stance",
      name: "Regional Coordination",
      description:
        "How much the denomination equips regions to share plans, staff, and learning across congregations.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.45, isActive: false, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 7 },
      enactmentCost: { resourceId: "authority", amount: 7 },
      repealCost: { resourceId: "authority", amount: 3 },
    },
    {
      id: "digital-ministry",
      type: "stance",
      name: "Digital Ministry",
      description:
        "The priority given to accessible online worship, teaching, and pastoral connection.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.35, isActive: false, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 8 },
      enactmentCost: { resourceId: "authority", amount: 8 },
      repealCost: { resourceId: "authority", amount: 4 },
    },
    {
      id: "stewardship-transparency",
      type: "stance",
      name: "Stewardship Transparency",
      description:
        "How openly leaders explain budgets, giving, and the use of denominational funds.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.5, isActive: true, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "money", base: 0.5, perPoint: 6 },
      enactmentCost: { resourceId: "authority", amount: 4 },
      repealCost: { resourceId: "authority", amount: 2 },
    },
    {
      id: "catechesis",
      type: "stance",
      name: "Catechesis",
      description:
        "The depth and consistency of instruction that helps members understand and practice the faith.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.5, isActive: true, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 8 },
      enactmentCost: { resourceId: "authority", amount: 4 },
      repealCost: { resourceId: "authority", amount: 2 },
    },
    {
      id: "liturgical-formation",
      type: "stance",
      name: "Liturgical Formation",
      description:
        "The attention given to forming congregations in shared worship practices and their meaning.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.55, isActive: true, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 7 },
      enactmentCost: { resourceId: "authority", amount: 5 },
      repealCost: { resourceId: "authority", amount: 2 },
    },
    {
      id: "ecumenical-dialogue",
      type: "stance",
      name: "Ecumenical Dialogue",
      description:
        "The priority given to sustained relationship and cooperation with other Christian communities.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.35, isActive: false, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 9 },
      enactmentCost: { resourceId: "authority", amount: 6 },
      repealCost: { resourceId: "authority", amount: 3 },
    },
    {
      id: "social-teaching-initiative",
      type: "stance",
      name: "Social Teaching Initiative",
      description:
        "The priority given to applying Christian social teaching through public witness and local service.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.4, isActive: false, isForced: false },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 9 },
      enactmentCost: { resourceId: "authority", amount: 7 },
      repealCost: { resourceId: "authority", amount: 3 },
    },
    {
      id: "newcomer-welcome",
      type: "indicator",
      name: "Newcomer Welcome",
      description:
        "How readily unfamiliar households find belonging, support, and a path into congregational life.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.45, isActive: true, isForced: true },
      baseline: 0.16,
    },
    {
      id: "volunteer-health",
      type: "indicator",
      name: "Volunteer Health",
      description:
        "The resilience and availability of members who sustain unpaid ministry and care work.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.48, isActive: true, isForced: true },
      baseline: 0.2,
    },
    {
      id: "giving-strength",
      type: "indicator",
      name: "Giving Strength",
      description:
        "The reliability of congregational giving relative to the fellowship’s commitments.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.54, isActive: true, isForced: true },
      baseline: 0.2,
    },
    {
      id: "rural-congregations-satisfaction",
      type: "faction",
      name: "Rural Congregations — Satisfaction",
      description: "Members of rural congregations.",
      category: "Governance",
      factionCategory: "geographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.46,
        isActive: true,
        isForced: true,
      },
      baseline: 0.32,
    },
    {
      id: "rural-congregations-membership",
      type: "faction",
      name: "Rural Congregations — Membership",
      description: "Members of rural congregations.",
      category: "Governance",
      factionCategory: "geographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.4,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "urban-missionaries-satisfaction",
      type: "faction",
      name: "Urban Missionaries — Satisfaction",
      description: "Ministers and members serving urban communities.",
      category: "Mission and Expansion",
      factionCategory: "geographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.42,
        isActive: true,
        isForced: true,
      },
      baseline: 0.24,
    },
    {
      id: "urban-missionaries-membership",
      type: "faction",
      name: "Urban Missionaries — Membership",
      description: "Ministers and members serving urban communities.",
      category: "Mission and Expansion",
      factionCategory: "geographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.3,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "volunteer-fatigue",
      type: "situation",
      name: "Volunteer Fatigue",
      description:
        "Repeated demands on a small pool of leaders are making service difficult to sustain.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.26, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.62,
      stopThreshold: 0.4,
    },
    {
      id: "isolation-risk",
      type: "situation",
      name: "Isolation Risk",
      description:
        "Households and congregations are losing connection to the wider fellowship.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.28, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.6,
      stopThreshold: 0.38,
    },
    {
      id: "revenue",
      type: "indicator",
      name: "Revenue",
      description:
        "Recurring income generated through congregational giving and trusted stewardship.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.56, isActive: true, isForced: true },
      baseline: 0.2,
    },
    {
      id: "expenditure",
      type: "indicator",
      name: "Expenditure",
      description:
        "The ongoing share of available capacity committed to ministry, care, and administration.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.5, isActive: true, isForced: true },
      baseline: 0.18,
    },
    {
      id: "confessional-members-satisfaction",
      type: "faction",
      name: "Confessional Members — Satisfaction",
      description: "Members with confessional convictions.",
      category: "Belief and Teaching",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.55,
        isActive: true,
        isForced: true,
      },
      baseline: 0.25,
    },
    {
      id: "confessional-members-membership",
      type: "faction",
      name: "Confessional Members — Membership",
      description: "Members with confessional convictions.",
      category: "Belief and Teaching",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.35,
        isActive: true,
        isForced: true,
      },
      constraintId: "confessional-boundaries",
    },
    {
      id: "ecumenical-members-satisfaction",
      type: "faction",
      name: "Ecumenical Members — Satisfaction",
      description: "Members who support ecumenical ties.",
      category: "Belief and Teaching",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.5,
        isActive: true,
        isForced: true,
      },
      baseline: 0.25,
    },
    {
      id: "ecumenical-members-membership",
      type: "faction",
      name: "Ecumenical Members — Membership",
      description: "Members who support ecumenical ties.",
      category: "Belief and Teaching",
      factionCategory: "theological",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.3,
        isActive: true,
        isForced: true,
      },
      constraintId: "confessional-boundaries",
    },
    {
      id: "youth-members-satisfaction",
      type: "faction",
      name: "Youth Members — Satisfaction",
      description: "Younger members.",
      category: "Worship and Practice",
      factionCategory: "demographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.45,
        isActive: true,
        isForced: true,
      },
      baseline: 0.25,
    },
    {
      id: "youth-members-membership",
      type: "faction",
      name: "Youth Members — Membership",
      description: "Younger members.",
      category: "Worship and Practice",
      factionCategory: "demographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.2,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "student-members-satisfaction",
      type: "faction",
      name: "Student Members — Satisfaction",
      description: "Members in education.",
      category: "Belief and Teaching",
      factionCategory: "demographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.5,
        isActive: true,
        isForced: true,
      },
      baseline: 0.25,
    },
    {
      id: "student-members-membership",
      type: "faction",
      name: "Student Members — Membership",
      description: "Members in education.",
      category: "Belief and Teaching",
      factionCategory: "demographic",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.15,
        isActive: true,
        isForced: true,
      },
    },
    {
      id: "clergy-members-satisfaction",
      type: "faction",
      name: "Clergy — Satisfaction",
      description: "Ordained clergy.",
      category: "Governance",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.55,
        isActive: true,
        isForced: true,
      },
      baseline: 0.25,
    },
    {
      id: "clergy-members-membership",
      type: "faction",
      name: "Clergy — Membership",
      description: "Ordained clergy.",
      category: "Governance",
      factionCategory: "institutional",
      domain: {
        min: 0,
        max: 1,
        clamp: true,
      },
      initial: {
        value: 0.08,
        isActive: true,
        isForced: true,
      },
    },
  ],
  effects: [
    {
      id: "centralization-to-reach",
      source: "centralization",
      target: "governance-reach",
      response: { kind: "linear", coefficient: 0.75 },
      label: "coordination",
    },
    {
      id: "centralization-to-localists",
      source: "centralization",
      target: "localist-movement",
      response: { kind: "linear", coefficient: 0.35 },
      inertiaTurns: 2,
      label: "resistance",
    },
    {
      id: "formation-to-quality",
      source: "clergy-formation",
      target: "clergy-quality",
      response: { kind: "linear", coefficient: 0.65 },
      inertiaTurns: 3,
      label: "formation pipeline",
    },
    {
      id: "reach-to-trust",
      source: "governance-reach",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: 0.35 },
      inertiaTurns: 2,
      label: "institutional competence",
    },
    {
      id: "trust-to-cohesion",
      source: "leadership-trust",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.35 },
      label: "confidence",
    },
    {
      id: "localists-to-cohesion",
      source: "localist-movement",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: -0.2 },
      label: "organized governance conflict",
    },
    {
      id: "governance-tension-baseline",
      source: "_default_",
      target: "governance-tension",
      response: { kind: "constant", value: 0.41575 },
    },
    {
      id: "localists-to-tension",
      source: "localist-movement",
      target: "governance-tension",
      response: { kind: "linear", coefficient: 0.3 },
      label: "autonomy demands",
    },
    {
      id: "shortage-baseline",
      source: "_default_",
      target: "clergy-shortage",
      response: { kind: "constant", value: 0.74 },
    },
    {
      id: "quality-to-shortage",
      source: "clergy-quality",
      target: "clergy-shortage",
      response: { kind: "linear", coefficient: -0.75 },
      label: "prepared clergy supply",
    },
    {
      id: "tension-to-trust",
      source: "governance-tension",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.22 },
      label: "public conflict",
    },
    {
      id: "shortage-to-trust",
      source: "clergy-shortage",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.12 },
      label: "unfilled pulpits",
    },
    {
      id: "reach-to-institutional-authority",
      source: "governance-reach",
      target: "institutional-authority",
      response: { kind: "linear", coefficient: 0.25 },
      label: "coordination capacity",
    },
    {
      id: "trust-to-institutional-authority",
      source: "leadership-trust",
      target: "institutional-authority",
      response: { kind: "linear", coefficient: 0.25 },
      label: "leadership legitimacy",
    },
    {
      id: "localists-to-institutional-authority",
      source: "localist-movement",
      target: "institutional-authority",
      response: { kind: "linear", coefficient: -0.12 },
      label: "contested authority",
    },
    {
      id: "institutional-authority-to-authority-resource",
      source: "institutional-authority",
      target: "authority",
      response: { kind: "linear", coefficient: 10 },
      label: "usable institutional latitude",
    },
    {
      id: "worship-to-participation",
      source: "worship-practice",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.62 },
      inertiaTurns: 2,
      label: "shared practice",
    },
    {
      id: "worship-to-traditionalists",
      source: "worship-practice",
      target: "traditionalist-coalition-satisfaction",
      response: { kind: "linear", coefficient: 0.24 },
      inertiaTurns: 2,
      label: "traditional observance",
    },
    {
      id: "participation-to-retention",
      source: "worship-participation",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "regular attendance",
    },
    {
      id: "participation-to-cohesion",
      source: "worship-participation",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.18 },
      label: "common worship",
    },
    {
      id: "worship-to-renewal",
      source: "worship-practice",
      target: "renewal-network-satisfaction",
      response: { kind: "linear", coefficient: -0.16 },
      inertiaTurns: 2,
      label: "traditionalist concern",
    },
    {
      id: "charity-to-impact",
      source: "charitable-commitment",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.68 },
      inertiaTurns: 3,
      label: "charity program",
    },
    {
      id: "impact-to-retention",
      source: "charitable-impact",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.25 },
      label: "visible care",
    },
    {
      id: "impact-to-lay-leadership",
      source: "charitable-impact",
      target: "lay-leadership-satisfaction",
      response: { kind: "linear", coefficient: 0.22 },
      label: "shared service",
    },
    {
      id: "impact-to-cohesion",
      source: "charitable-impact",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.18 },
      label: "care networks",
    },
    {
      id: "outreach-to-reach",
      source: "missionary-outreach",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.7 },
      inertiaTurns: 3,
      label: "mission investment",
    },
    {
      id: "reach-to-renewal",
      source: "mission-reach",
      target: "renewal-network-satisfaction",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "renewal energy",
    },
    {
      id: "reach-to-retention",
      source: "mission-reach",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "new members",
    },
    {
      id: "reach-to-cohesion",
      source: "mission-reach",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.12 },
      label: "outward purpose",
    },
    {
      id: "discipline-to-stability",
      source: "financial-discipline",
      target: "financial-stability",
      response: { kind: "linear", coefficient: 0.62 },
      inertiaTurns: 2,
      label: "stewardship",
    },
    {
      id: "traditionalists-to-worship",
      source: "traditionalist-coalition-satisfaction",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.2 },
      label: "traditional confidence",
    },
    {
      id: "traditionalists-to-cohesion",
      source: "traditionalist-coalition-satisfaction",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.1 },
      label: "continuity",
    },
    {
      id: "renewal-to-mission",
      source: "renewal-network-satisfaction",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.2 },
      label: "renewal initiatives",
    },
    {
      id: "renewal-to-charity",
      source: "renewal-network-satisfaction",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.16 },
      label: "renewal service",
    },
    {
      id: "lay-to-retention",
      source: "lay-leadership-satisfaction",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "local leadership",
    },
    {
      id: "lay-to-charity",
      source: "lay-leadership-satisfaction",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 2,
      label: "volunteer capacity",
    },
    {
      id: "lay-to-cohesion",
      source: "lay-leadership-satisfaction",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.2 },
      label: "congregational ownership",
    },
    {
      id: "membership-decline-pressure",
      source: "_default_",
      target: "membership-decline",
      response: { kind: "constant", value: 0.72 },
      label: "demographic pressure",
    },
    {
      id: "retention-to-membership-decline",
      source: "member-retention",
      target: "membership-decline",
      response: { kind: "linear", coefficient: -0.86 },
      inertiaTurns: 2,
      label: "retained households",
    },
    {
      id: "membership-decline-to-trust",
      source: "membership-decline",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.12 },
      inertiaTurns: 2,
      label: "shrinking base",
    },
    {
      id: "financial-strain-pressure",
      source: "_default_",
      target: "financial-strain",
      response: { kind: "constant", value: 0.7 },
      label: "fixed obligations",
    },
    {
      id: "stability-to-financial-strain",
      source: "financial-stability",
      target: "financial-strain",
      response: { kind: "linear", coefficient: -0.85 },
      inertiaTurns: 2,
      label: "solvent operations",
    },
    {
      id: "financial-strain-to-trust",
      source: "financial-strain",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.1 },
      inertiaTurns: 2,
      label: "financial anxiety",
    },
    {
      id: "reach-of-governance-to-lay",
      source: "governance-reach",
      target: "lay-leadership-satisfaction",
      response: { kind: "linear", coefficient: 0.18 },
      label: "coordinated service",
    },
    {
      id: "centralization-to-lay",
      source: "centralization",
      target: "lay-leadership-satisfaction",
      response: { kind: "linear", coefficient: -0.2 },
      inertiaTurns: 2,
      label: "local autonomy",
    },
    {
      id: "clergy-quality-to-mission",
      source: "clergy-quality",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 3,
      label: "trained mission workers",
    },
    {
      id: "clergy-quality-to-participation",
      source: "clergy-quality",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.15 },
      inertiaTurns: 3,
      label: "pastoral formation",
    },
    {
      id: "partnerships-to-charity",
      source: "community-partnerships",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 2,
      label: "shared local service",
    },
    {
      id: "partnerships-to-vitality",
      source: "community-partnerships",
      target: "regional-vitality",
      response: { kind: "linear", coefficient: 0.26 },
      inertiaTurns: 2,
      label: "community presence",
    },
    {
      id: "youth-formation-to-engagement",
      source: "youth-formation",
      target: "youth-engagement",
      response: { kind: "linear", coefficient: 0.62 },
      inertiaTurns: 3,
      label: "mentoring and formation",
    },
    {
      id: "participation-to-youth-engagement",
      source: "worship-participation",
      target: "youth-engagement",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "welcoming worship",
    },
    {
      id: "youth-engagement-to-leaders",
      source: "youth-engagement",
      target: "emerging-leaders-satisfaction",
      response: { kind: "linear", coefficient: 0.32 },
      inertiaTurns: 3,
      label: "leadership pipeline",
    },
    {
      id: "leaders-to-lay-leadership",
      source: "emerging-leaders-satisfaction",
      target: "lay-leadership-satisfaction",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 2,
      label: "new local leaders",
    },
    {
      id: "youth-engagement-to-vitality",
      source: "youth-engagement",
      target: "regional-vitality",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "intergenerational participation",
    },
    {
      id: "vitality-to-retention",
      source: "regional-vitality",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "healthy local congregations",
    },
    {
      id: "stability-to-capacity",
      source: "financial-stability",
      target: "ministry-capacity",
      response: { kind: "linear", coefficient: 0.55 },
      inertiaTurns: 2,
      label: "sustainable staffing",
    },
    {
      id: "capacity-to-mission",
      source: "ministry-capacity",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.35 },
      inertiaTurns: 2,
      label: "room for new ministry",
    },
    {
      id: "transparency-to-giving",
      source: "stewardship-transparency",
      target: "giving-strength",
      response: { kind: "linear", coefficient: 0.34 },
      inertiaTurns: 2,
      label: "trusted stewardship",
    },
    {
      id: "discipline-to-giving",
      source: "financial-discipline",
      target: "giving-strength",
      response: { kind: "linear", coefficient: 0.22 },
      label: "sustainable budgets",
    },
    {
      id: "giving-to-revenue",
      source: "giving-strength",
      target: "revenue",
      response: { kind: "linear", coefficient: 0.42 },
      inertiaTurns: 2,
      label: "congregational giving",
    },
    {
      id: "revenue-to-money",
      source: "revenue",
      target: "money",
      response: { kind: "linear", coefficient: 20 },
      inertiaTurns: 2,
      label: "income available",
    },
    {
      id: "expenditure-to-money",
      source: "expenditure",
      target: "money",
      response: { kind: "linear", coefficient: -20 },
      inertiaTurns: 2,
      label: "committed spending",
    },
    {
      id: "charity-to-expenditure",
      source: "charitable-commitment",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.15 },
      inertiaTurns: 2,
      label: "care commitments",
    },
    {
      id: "mission-to-expenditure",
      source: "missionary-outreach",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.14 },
      inertiaTurns: 2,
      label: "outreach commitments",
    },
    {
      id: "formation-to-expenditure",
      source: "youth-formation",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.12 },
      inertiaTurns: 2,
      label: "formation commitments",
    },
    {
      id: "partnerships-to-expenditure",
      source: "community-partnerships",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.12 },
      inertiaTurns: 2,
      label: "partner commitments",
    },
    {
      id: "digital-to-expenditure",
      source: "digital-ministry",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.1 },
      inertiaTurns: 2,
      label: "digital infrastructure",
    },
    {
      id: "discipline-to-expenditure",
      source: "financial-discipline",
      target: "expenditure",
      response: { kind: "linear", coefficient: -0.1 },
      inertiaTurns: 2,
      label: "spending controls",
    },
    {
      id: "money-to-stability",
      source: "money",
      target: "financial-stability",
      response: { kind: "linear", coefficient: 0.006 },
      inertiaTurns: 2,
      label: "available reserves",
    },
    {
      id: "money-to-capacity",
      source: "money",
      target: "ministry-capacity",
      response: { kind: "linear", coefficient: 0.004 },
      inertiaTurns: 2,
      label: "funded ministry",
    },
    {
      id: "regional-coordination-to-vitality",
      source: "regional-coordination",
      target: "regional-vitality",
      response: { kind: "linear", coefficient: 0.38 },
      inertiaTurns: 2,
      label: "shared regional learning",
    },
    {
      id: "coordination-to-rural",
      source: "regional-coordination",
      target: "rural-congregations-satisfaction",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "rural support",
    },
    {
      id: "digital-to-welcome",
      source: "digital-ministry",
      target: "newcomer-welcome",
      response: { kind: "linear", coefficient: 0.28 },
      inertiaTurns: 2,
      label: "accessible connection",
    },
    {
      id: "digital-to-mission",
      source: "digital-ministry",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "distributed mission",
    },
    {
      id: "digital-to-urban",
      source: "digital-ministry",
      target: "urban-missionaries-satisfaction",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "urban experimentation",
    },
    {
      id: "partnerships-to-welcome",
      source: "community-partnerships",
      target: "newcomer-welcome",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "neighbors at the table",
    },
    {
      id: "welcome-to-retention",
      source: "newcomer-welcome",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.28 },
      inertiaTurns: 2,
      label: "belonging",
    },
    {
      id: "capacity-to-volunteers",
      source: "ministry-capacity",
      target: "volunteer-health",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "supported volunteers",
    },
    {
      id: "volunteers-to-charity",
      source: "volunteer-health",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.24 },
      inertiaTurns: 2,
      label: "hands for service",
    },
    {
      id: "volunteers-to-welcome",
      source: "volunteer-health",
      target: "newcomer-welcome",
      response: { kind: "linear", coefficient: 0.2 },
      label: "open doors",
    },
    {
      id: "fatigue-pressure",
      source: "_default_",
      target: "volunteer-fatigue",
      response: { kind: "constant", value: 0.68 },
      label: "limited leaders",
    },
    {
      id: "volunteers-to-fatigue",
      source: "volunteer-health",
      target: "volunteer-fatigue",
      response: { kind: "linear", coefficient: -0.72 },
      inertiaTurns: 2,
      label: "healthy rotation",
    },
    {
      id: "fatigue-to-capacity",
      source: "volunteer-fatigue",
      target: "ministry-capacity",
      response: { kind: "linear", coefficient: -0.18 },
      inertiaTurns: 2,
      label: "burned-out teams",
    },
    {
      id: "isolation-pressure",
      source: "_default_",
      target: "isolation-risk",
      response: { kind: "constant", value: 0.66 },
      label: "distance and fragmentation",
    },
    {
      id: "retention-to-isolation",
      source: "member-retention",
      target: "isolation-risk",
      response: { kind: "linear", coefficient: -0.78 },
      inertiaTurns: 2,
      label: "connected households",
    },
    {
      id: "isolation-to-cohesion",
      source: "isolation-risk",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: -0.24 },
      inertiaTurns: 2,
      label: "fragmented fellowship",
    },
    {
      id: "vitality-to-rural",
      source: "regional-vitality",
      target: "rural-congregations-satisfaction",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "regional resilience",
    },
    {
      id: "vitality-to-urban",
      source: "regional-vitality",
      target: "urban-missionaries-satisfaction",
      response: { kind: "linear", coefficient: 0.16 },
      inertiaTurns: 2,
      label: "shared momentum",
    },
    {
      id: "rural-to-participation",
      source: "rural-congregations-satisfaction",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.14 },
      label: "local continuity",
    },
    {
      id: "urban-to-mission",
      source: "urban-missionaries-satisfaction",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.2 },
      label: "contextual mission",
    },
    {
      id: "catechesis-to-youth-engagement",
      source: "catechesis",
      target: "youth-engagement",
      response: { kind: "linear", coefficient: 0.28 },
      inertiaTurns: 2,
      label: "grounded formation",
    },
    {
      id: "catechesis-to-retention",
      source: "catechesis",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.16 },
      inertiaTurns: 2,
      label: "formed belonging",
    },
    {
      id: "liturgical-formation-to-participation",
      source: "liturgical-formation",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "formed worship",
    },
    {
      id: "liturgical-formation-to-traditionalists",
      source: "liturgical-formation",
      target: "traditionalist-coalition-satisfaction",
      response: { kind: "linear", coefficient: 0.16 },
      inertiaTurns: 2,
      label: "liturgical continuity",
    },
    {
      id: "liturgical-formation-to-welcome",
      source: "liturgical-formation",
      target: "newcomer-welcome",
      response: { kind: "linear", coefficient: 0.08 },
      inertiaTurns: 2,
      label: "shared practice",
    },
    {
      id: "ecumenical-dialogue-to-charity",
      source: "ecumenical-dialogue",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "shared witness",
    },
    {
      id: "ecumenical-dialogue-to-renewal",
      source: "ecumenical-dialogue",
      target: "renewal-network-satisfaction",
      response: { kind: "linear", coefficient: 0.15 },
      inertiaTurns: 2,
      label: "wider fellowship",
    },
    {
      id: "ecumenical-dialogue-to-traditionalists",
      source: "ecumenical-dialogue",
      target: "traditionalist-coalition-satisfaction",
      response: { kind: "linear", coefficient: -0.1 },
      inertiaTurns: 2,
      label: "ecumenical concern",
    },
    {
      id: "social-teaching-to-charity",
      source: "social-teaching-initiative",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.26 },
      inertiaTurns: 2,
      label: "public service",
    },
    {
      id: "social-teaching-to-lay-leadership",
      source: "social-teaching-initiative",
      target: "lay-leadership-satisfaction",
      response: { kind: "linear", coefficient: 0.16 },
      inertiaTurns: 2,
      label: "shared witness",
    },
    {
      id: "social-teaching-to-traditionalists",
      source: "social-teaching-initiative",
      target: "traditionalist-coalition-satisfaction",
      response: { kind: "linear", coefficient: -0.08 },
      inertiaTurns: 2,
      label: "social concern",
    },
    {
      id: "social-teaching-to-expenditure",
      source: "social-teaching-initiative",
      target: "expenditure",
      response: { kind: "linear", coefficient: 0.08 },
      inertiaTurns: 2,
      label: "public commitments",
    },
    {
      id: "clergy-formation-to-confessional-members",
      source: "clergy-formation",
      target: "confessional-members-satisfaction",
      response: { kind: "linear", coefficient: 0.3 },
    },
    {
      id: "ecumenical-dialogue-to-ecumenical-members",
      source: "ecumenical-dialogue",
      target: "ecumenical-members-satisfaction",
      response: { kind: "linear", coefficient: 0.3 },
    },
    {
      id: "youth-engagement-to-youth-members",
      source: "youth-engagement",
      target: "youth-members-satisfaction",
      response: { kind: "linear", coefficient: 0.4 },
    },
    {
      id: "clergy-quality-to-student-members",
      source: "clergy-quality",
      target: "student-members-satisfaction",
      response: { kind: "linear", coefficient: 0.3 },
    },
    {
      id: "leadership-trust-to-clergy-members",
      source: "leadership-trust",
      target: "clergy-members-satisfaction",
      response: { kind: "linear", coefficient: 0.35 },
    },
    {
      id: "rural-congregations-to-autonomy-campaign",
      source: "rural-congregations-satisfaction",
      target: "localist-movement",
      response: { kind: "linear", intercept: 0.25, coefficient: -0.25 },
      label: "constituency dissatisfaction",
    },
    {
      id: "urban-missionaries-to-autonomy-campaign",
      source: "urban-missionaries-satisfaction",
      target: "localist-movement",
      response: { kind: "linear", intercept: 0.25, coefficient: -0.25 },
      label: "constituency dissatisfaction",
    },
    {
      id: "youth-engagement-to-youth-membership",
      source: "youth-engagement",
      target: "youth-members-membership",
      response: { kind: "linear", coefficient: 0.05 },
      inertiaTurns: 2,
    },
  ],
} as const satisfies ScenarioDefinition;
