import type { ScenarioDefinition } from '../../simulation'

const percentDomain = { min: 0, max: 1, clamp: true } as const

export const exampleScenario = {
  id: 'connectional-fellowship-1980',
  title: 'The Connectional Fellowship',
  description:
    'Guide a growing fellowship through competing demands for institutional strength, local trust, and clergy formation.',
  startingTurn: 0,
  startingYear: 1980,
  prerequisites: ['_has_seminary', '_has_general_assembly'],
  nodes: [
    {
      id: 'centralization',
      type: 'stance',
      name: 'Centralization',
      description: 'How much authority is concentrated in the central church office.',
      category: 'Governance',
      domain: percentDomain,
      initialValue: 0.55,
      activation: 'forced-active',
      control: { kind: 'continuous', step: 0.05 },
      cost: {
        resourceId: 'authority',
        base: 0.5,
        perPoint: 12,
        maxChange: 0.2,
      },
    },
    {
      id: 'clergy-formation',
      type: 'stance',
      name: 'Clergy Formation',
      description: 'The rigor and institutional investment required for clergy formation.',
      category: 'Belief and Teaching',
      domain: percentDomain,
      initialValue: 0.6,
      activation: 'forced-active',
      control: { kind: 'continuous', step: 0.05 },
      prerequisites: ['_has_seminary'],
      cost: {
        resourceId: 'authority',
        base: 0.5,
        perPoint: 10,
        maxChange: 0.2,
      },
    },
    {
      id: 'governance-reach',
      type: 'indicator',
      name: 'Governance Reach',
      description: 'The central institution’s ability to coordinate congregations.',
      category: 'Governance',
      domain: percentDomain,
      initialValue: 0.5325,
      baselineValue: 0.12,
      activation: 'forced-active',
    },
    {
      id: 'leadership-trust',
      type: 'indicator',
      name: 'Leadership Trust',
      description: 'Confidence in denominational leadership.',
      category: 'Governance',
      domain: percentDomain,
      initialValue: 0.436,
      baselineValue: 0.25,
      activation: 'forced-active',
    },
    {
      id: 'congregational-cohesion',
      type: 'indicator',
      name: 'Congregational Cohesion',
      description: 'The denomination’s ability to remain connected despite disagreement.',
      category: 'Care and Charity',
      domain: percentDomain,
      initialValue: 0.646,
      baselineValue: 0.35,
      activation: 'forced-active',
    },
    {
      id: 'clergy-quality',
      type: 'indicator',
      name: 'Clergy Quality',
      description: 'The preparation and effectiveness of active clergy.',
      category: 'Belief and Teaching',
      domain: percentDomain,
      initialValue: 0.57,
      baselineValue: 0.18,
      activation: 'forced-active',
    },
    {
      id: 'localist-movement',
      type: 'faction',
      name: 'Localist Movement',
      description: 'Congregations committed to meaningful local autonomy.',
      category: 'Governance',
      domain: percentDomain,
      initialValue: 0.4775,
      baselineValue: 0.78,
      activation: 'active',
      valueMeaning: 'approval',
    },
    {
      id: 'authority',
      type: 'resource',
      name: 'Authority',
      description: 'Institutional latitude available for changing established Stances.',
      category: 'Governance',
      domain: { min: 0, max: 100, clamp: true },
      initialValue: 48.5,
      baselineValue: 45,
      activation: 'forced-active',
      graphVisible: false,
    },
    {
      id: 'governance-tension',
      type: 'situation',
      name: 'Governance Tension',
      description: 'Organized resistance to central direction has become persistent.',
      category: 'Governance',
      domain: percentDomain,
      initialValue: 0.41575,
      baselineValue: 0,
      activation: 'inactive',
      startThreshold: 0.58,
      stopThreshold: 0.42,
    },
    {
      id: 'clergy-shortage',
      type: 'situation',
      name: 'Clergy Shortage',
      description: 'The available supply of well-prepared clergy is insufficient.',
      category: 'Belief and Teaching',
      domain: percentDomain,
      initialValue: 0.3125,
      baselineValue: 0,
      activation: 'inactive',
      startThreshold: 0.58,
      stopThreshold: 0.4,
    },
  ],
  effects: [
    {
      id: 'centralization-to-reach',
      source: 'centralization',
      target: 'governance-reach',
      response: { kind: 'linear', coefficient: 0.75 },
      label: 'coordination',
    },
    {
      id: 'centralization-to-localists',
      source: 'centralization',
      target: 'localist-movement',
      response: { kind: 'linear', coefficient: -0.55 },
      inertiaTurns: 2,
      label: 'resistance',
    },
    {
      id: 'formation-to-quality',
      source: 'clergy-formation',
      target: 'clergy-quality',
      response: { kind: 'linear', coefficient: 0.65 },
      inertiaTurns: 3,
      label: 'formation pipeline',
    },
    {
      id: 'reach-to-trust',
      source: 'governance-reach',
      target: 'leadership-trust',
      response: { kind: 'linear', coefficient: 0.35 },
      inertiaTurns: 2,
      label: 'institutional competence',
    },
    {
      id: 'trust-to-cohesion',
      source: 'leadership-trust',
      target: 'congregational-cohesion',
      response: { kind: 'linear', coefficient: 0.35 },
      label: 'confidence',
    },
    {
      id: 'localists-to-cohesion',
      source: 'localist-movement',
      target: 'congregational-cohesion',
      response: { kind: 'linear', coefficient: 0.3 },
      label: 'local participation',
    },
    {
      id: 'governance-tension-baseline',
      source: '_default_',
      target: 'governance-tension',
      response: { kind: 'constant', value: 0.75 },
    },
    {
      id: 'localists-to-tension',
      source: 'localist-movement',
      target: 'governance-tension',
      response: { kind: 'linear', coefficient: -0.7 },
      label: 'represented concerns',
    },
    {
      id: 'shortage-baseline',
      source: '_default_',
      target: 'clergy-shortage',
      response: { kind: 'constant', value: 0.74 },
    },
    {
      id: 'quality-to-shortage',
      source: 'clergy-quality',
      target: 'clergy-shortage',
      response: { kind: 'linear', coefficient: -0.75 },
      label: 'prepared clergy supply',
    },
    {
      id: 'tension-to-trust',
      source: 'governance-tension',
      target: 'leadership-trust',
      response: { kind: 'linear', coefficient: -0.22 },
      label: 'public conflict',
    },
    {
      id: 'shortage-to-trust',
      source: 'clergy-shortage',
      target: 'leadership-trust',
      response: { kind: 'linear', coefficient: -0.12 },
      label: 'unfilled pulpits',
    },
    {
      id: 'trust-to-authority',
      source: 'leadership-trust',
      target: 'authority',
      response: { kind: 'linear', coefficient: 8 },
      label: 'institutional confidence',
    },
  ],
  events: [
    {
      id: 'prominent-resignation',
      kind: 'event',
      title: 'A Prominent Cleric Resigns',
      description:
        'A respected cleric cites the strain caused by persistent vacancies.',
      influences: [
        { source: 'clergy-shortage', coefficient: 1 },
        { source: '_random_', coefficient: 0.08 },
      ],
      threshold: 0.62,
      cooldownTurns: 8,
      consequences: [
        {
          kind: 'grudge',
          target: 'leadership-trust',
          magnitude: -0.12,
          decay: 0.86,
          label: 'Aftermath of a prominent resignation',
        },
      ],
    },
  ],
  dilemmas: [
    {
      id: 'local-resistance',
      kind: 'dilemma',
      title: 'Local Resistance Organizes',
      description:
        'Several congregations demand a clear response to the expansion of central authority.',
      influences: [{ source: 'governance-tension', coefficient: 1 }],
      threshold: 0.58,
      cooldownTurns: 10,
      choices: [
        {
          id: 'assert-authority',
          label: 'Assert central authority',
          description: 'Spend Authority to hold the institutional line.',
          consequences: [
            { kind: 'resource', target: 'authority', amount: -6 },
            {
              kind: 'grudge',
              target: 'governance-reach',
              magnitude: 0.08,
              decay: 0.82,
              label: 'Clear central direction',
            },
            {
              kind: 'grudge',
              target: 'localist-movement',
              magnitude: -0.1,
              decay: 0.9,
              label: 'Congregations overruled',
            },
          ],
        },
        {
          id: 'recognize-autonomy',
          label: 'Recognize local autonomy',
          description: 'Reassure congregations while accepting weaker coordination.',
          consequences: [
            {
              kind: 'grudge',
              target: 'localist-movement',
              magnitude: 0.12,
              decay: 0.88,
              label: 'Local prerogatives recognized',
            },
            {
              kind: 'grudge',
              target: 'governance-reach',
              magnitude: -0.08,
              decay: 0.84,
              label: 'Central hesitation',
            },
          ],
        },
        {
          id: 'mediate',
          label: 'Fund mediation',
          description: 'Spend modest Authority to rebuild cohesion.',
          consequences: [
            { kind: 'resource', target: 'authority', amount: -3 },
            {
              kind: 'grudge',
              target: 'congregational-cohesion',
              magnitude: 0.09,
              decay: 0.85,
              label: 'Patient mediation',
            },
          ],
        },
      ],
    },
  ],
} as const satisfies ScenarioDefinition
