import type { ScenarioDefinition } from "../../simulation";

const percentDomain = { min: 0, max: 1, clamp: true } as const;

export const exampleScenario = {
  id: "connectional-fellowship-1980",
  title: "The Connectional Fellowship",
  description:
    "Guide a growing fellowship through competing demands for institutional strength, local trust, ministry investment, and sustainable mission.",
  schemaVersion: 1,
  start: { turn: 0, year: 1980 },
  conditions: ["has-seminary", "has-general-assembly"],
  nodes: [
    {
      id: "centralization",
      type: "stance",
      name: "Centralization",
      description:
        "How much authority is concentrated in the central church office.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.55, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: {
        resourceId: "authority",
        base: 0.5,
        perPoint: 12,
      },
    },
    {
      id: "clergy-formation",
      type: "stance",
      name: "Clergy Formation",
      description:
        "The rigor and institutional investment required for clergy formation.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.6, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      requires: ["has-seminary"],
      cost: {
        resourceId: "authority",
        base: 0.5,
        perPoint: 10,
      },
    },
    {
      id: "governance-reach",
      type: "indicator",
      name: "Governance Reach",
      description:
        "The central institution’s ability to coordinate congregations.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.5325, isActive: true, isForced: true },
      baseline: 0.12,
    },
    {
      id: "leadership-trust",
      type: "indicator",
      name: "Leadership Trust",
      description: "Confidence in denominational leadership.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.436, isActive: true, isForced: true },
      baseline: 0.25,
    },
    {
      id: "congregational-cohesion",
      type: "indicator",
      name: "Congregational Cohesion",
      description:
        "The denomination’s ability to remain connected despite disagreement.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.646, isActive: true, isForced: true },
      baseline: 0.35,
    },
    {
      id: "clergy-quality",
      type: "indicator",
      name: "Clergy Quality",
      description: "The preparation and effectiveness of active clergy.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.57, isActive: true, isForced: true },
      baseline: 0.18,
    },
    {
      id: "localist-movement",
      type: "faction",
      name: "Localist Movement",
      description: "Congregations committed to meaningful local autonomy.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.4775, isActive: true, isForced: false },
      baseline: 0.78,
      valueMeaning: "approval",
    },
    {
      id: "authority",
      type: "resource",
      name: "Authority",
      description:
        "Institutional latitude available for changing established Stances.",
      category: "Governance",
      domain: { min: 0, max: 100, clamp: true },
      initial: { value: 48.5, isActive: true, isForced: true },
      baseline: 45,
      graphVisible: false,
    },
    {
      id: "governance-tension",
      type: "situation",
      name: "Governance Tension",
      description:
        "Organized resistance to central direction has become persistent.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.41575, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.58,
      stopThreshold: 0.42,
    },
    {
      id: "clergy-shortage",
      type: "situation",
      name: "Clergy Shortage",
      description:
        "The available supply of well-prepared clergy is insufficient.",
      category: "Belief and Teaching",
      domain: percentDomain,
      initial: { value: 0.3125, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.58,
      stopThreshold: 0.4,
    },
    {
      id: "worship-practice",
      type: "stance",
      name: "Worship Practice",
      description:
        "How strongly congregations emphasize shared worship and inherited forms of practice.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.52, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 7 },
    },
    {
      id: "charitable-commitment",
      type: "stance",
      name: "Charitable Commitment",
      description:
        "The share of institutional attention and funding devoted to care for neighbors in need.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.48, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 8 },
    },
    {
      id: "missionary-outreach",
      type: "stance",
      name: "Missionary Outreach",
      description:
        "The denomination’s willingness to invest in ministry beyond its established congregations.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.42, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 9 },
    },
    {
      id: "financial-discipline",
      type: "stance",
      name: "Financial Discipline",
      description:
        "How firmly the denomination protects reserves and requires sustainable ministry budgets.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.58, isActive: true, isForced: true },
      control: { kind: "continuous", step: 0.05 },
      cost: { resourceId: "authority", base: 0.5, perPoint: 6 },
    },
    {
      id: "worship-participation",
      type: "indicator",
      name: "Worship Participation",
      description:
        "The consistency with which members gather for shared worship and practice.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.56, isActive: true, isForced: true },
      baseline: 0.24,
    },
    {
      id: "member-retention",
      type: "indicator",
      name: "Member Retention",
      description:
        "The denomination’s ability to keep households connected across changing seasons.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.62, isActive: true, isForced: true },
      baseline: 0.26,
    },
    {
      id: "charitable-impact",
      type: "indicator",
      name: "Charitable Impact",
      description:
        "The practical reach and perceived effectiveness of the denomination’s care ministries.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.49, isActive: true, isForced: true },
      baseline: 0.15,
    },
    {
      id: "mission-reach",
      type: "indicator",
      name: "Mission Reach",
      description:
        "The denomination’s ability to form new communities and serve beyond its existing base.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.44, isActive: true, isForced: true },
      baseline: 0.12,
    },
    {
      id: "financial-stability",
      type: "indicator",
      name: "Financial Stability",
      description:
        "The institution’s ability to meet commitments while sustaining ministry over time.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.56, isActive: true, isForced: true },
      baseline: 0.18,
    },
    {
      id: "traditionalist-coalition",
      type: "faction",
      name: "Traditionalist Coalition",
      description:
        "Members who value continuity, inherited worship, and familiar denominational forms.",
      category: "Worship and Practice",
      domain: percentDomain,
      initial: { value: 0.53, isActive: true, isForced: false },
      baseline: 0.6,
      valueMeaning: "approval",
    },
    {
      id: "renewal-network",
      type: "faction",
      name: "Renewal Network",
      description:
        "Members and ministers who favor experimentation, mission, and new forms of service.",
      category: "Mission and Expansion",
      domain: percentDomain,
      initial: { value: 0.47, isActive: true, isForced: false },
      baseline: 0.32,
      valueMeaning: "approval",
    },
    {
      id: "lay-leadership",
      type: "faction",
      name: "Lay Leadership",
      description:
        "The confidence and capacity of non-clergy members to carry local ministry.",
      category: "Governance",
      domain: percentDomain,
      initial: { value: 0.5, isActive: true, isForced: false },
      baseline: 0.4,
      valueMeaning: "confidence",
    },
    {
      id: "membership-decline",
      type: "situation",
      name: "Membership Decline",
      description:
        "A persistent loss of connected households threatens the fellowship’s local presence.",
      category: "Care and Charity",
      domain: percentDomain,
      initial: { value: 0.24, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.62,
      stopThreshold: 0.4,
    },
    {
      id: "financial-strain",
      type: "situation",
      name: "Financial Strain",
      description:
        "Operating commitments and weakened reserves are placing the ministry budget under pressure.",
      category: "Finance and Assets",
      domain: percentDomain,
      initial: { value: 0.22, isActive: false, isForced: false },
      baseline: 0,
      startThreshold: 0.6,
      stopThreshold: 0.38,
    },
  ],
  effects: [
    {
      id: "centralization-to-reach",
      source: "centralization",
      target: "governance-reach",
      response: { kind: "linear", coefficient: 0.75 },
      label: "coordination",
    },
    {
      id: "centralization-to-localists",
      source: "centralization",
      target: "localist-movement",
      response: { kind: "linear", coefficient: -0.55 },
      inertiaTurns: 2,
      label: "resistance",
    },
    {
      id: "formation-to-quality",
      source: "clergy-formation",
      target: "clergy-quality",
      response: { kind: "linear", coefficient: 0.65 },
      inertiaTurns: 3,
      label: "formation pipeline",
    },
    {
      id: "reach-to-trust",
      source: "governance-reach",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: 0.35 },
      inertiaTurns: 2,
      label: "institutional competence",
    },
    {
      id: "trust-to-cohesion",
      source: "leadership-trust",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.35 },
      label: "confidence",
    },
    {
      id: "localists-to-cohesion",
      source: "localist-movement",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.3 },
      label: "local participation",
    },
    {
      id: "governance-tension-baseline",
      source: "_default_",
      target: "governance-tension",
      response: { kind: "constant", value: 0.75 },
    },
    {
      id: "localists-to-tension",
      source: "localist-movement",
      target: "governance-tension",
      response: { kind: "linear", coefficient: -0.7 },
      label: "represented concerns",
    },
    {
      id: "shortage-baseline",
      source: "_default_",
      target: "clergy-shortage",
      response: { kind: "constant", value: 0.74 },
    },
    {
      id: "quality-to-shortage",
      source: "clergy-quality",
      target: "clergy-shortage",
      response: { kind: "linear", coefficient: -0.75 },
      label: "prepared clergy supply",
    },
    {
      id: "tension-to-trust",
      source: "governance-tension",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.22 },
      label: "public conflict",
    },
    {
      id: "shortage-to-trust",
      source: "clergy-shortage",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.12 },
      label: "unfilled pulpits",
    },
    {
      id: "trust-to-authority",
      source: "leadership-trust",
      target: "authority",
      response: { kind: "linear", coefficient: 8 },
      label: "institutional confidence",
    },
    {
      id: "worship-to-participation",
      source: "worship-practice",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.62 },
      inertiaTurns: 2,
      label: "shared practice",
    },
    {
      id: "worship-to-traditionalists",
      source: "worship-practice",
      target: "traditionalist-coalition",
      response: { kind: "linear", coefficient: 0.24 },
      inertiaTurns: 2,
      label: "traditional observance",
    },
    {
      id: "participation-to-retention",
      source: "worship-participation",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "regular attendance",
    },
    {
      id: "participation-to-cohesion",
      source: "worship-participation",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.18 },
      label: "common worship",
    },
    {
      id: "worship-to-renewal",
      source: "worship-practice",
      target: "renewal-network",
      response: { kind: "linear", coefficient: -0.16 },
      inertiaTurns: 2,
      label: "traditionalist concern",
    },
    {
      id: "charity-to-impact",
      source: "charitable-commitment",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.68 },
      inertiaTurns: 3,
      label: "charity program",
    },
    {
      id: "impact-to-retention",
      source: "charitable-impact",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.25 },
      label: "visible care",
    },
    {
      id: "impact-to-lay-leadership",
      source: "charitable-impact",
      target: "lay-leadership",
      response: { kind: "linear", coefficient: 0.22 },
      label: "shared service",
    },
    {
      id: "impact-to-cohesion",
      source: "charitable-impact",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.18 },
      label: "care networks",
    },
    {
      id: "outreach-to-reach",
      source: "missionary-outreach",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.7 },
      inertiaTurns: 3,
      label: "mission investment",
    },
    {
      id: "reach-to-renewal",
      source: "mission-reach",
      target: "renewal-network",
      response: { kind: "linear", coefficient: 0.3 },
      inertiaTurns: 2,
      label: "renewal energy",
    },
    {
      id: "reach-to-retention",
      source: "mission-reach",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.22 },
      inertiaTurns: 2,
      label: "new members",
    },
    {
      id: "reach-to-cohesion",
      source: "mission-reach",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.12 },
      label: "outward purpose",
    },
    {
      id: "discipline-to-stability",
      source: "financial-discipline",
      target: "financial-stability",
      response: { kind: "linear", coefficient: 0.62 },
      inertiaTurns: 2,
      label: "stewardship",
    },
    {
      id: "traditionalists-to-worship",
      source: "traditionalist-coalition",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.2 },
      label: "traditional confidence",
    },
    {
      id: "traditionalists-to-cohesion",
      source: "traditionalist-coalition",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.1 },
      label: "continuity",
    },
    {
      id: "renewal-to-mission",
      source: "renewal-network",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.2 },
      label: "renewal initiatives",
    },
    {
      id: "renewal-to-charity",
      source: "renewal-network",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.16 },
      label: "renewal service",
    },
    {
      id: "lay-to-retention",
      source: "lay-leadership",
      target: "member-retention",
      response: { kind: "linear", coefficient: 0.18 },
      inertiaTurns: 2,
      label: "local leadership",
    },
    {
      id: "lay-to-charity",
      source: "lay-leadership",
      target: "charitable-impact",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 2,
      label: "volunteer capacity",
    },
    {
      id: "lay-to-cohesion",
      source: "lay-leadership",
      target: "congregational-cohesion",
      response: { kind: "linear", coefficient: 0.2 },
      label: "congregational ownership",
    },
    {
      id: "membership-decline-pressure",
      source: "_default_",
      target: "membership-decline",
      response: { kind: "constant", value: 0.72 },
      label: "demographic pressure",
    },
    {
      id: "retention-to-membership-decline",
      source: "member-retention",
      target: "membership-decline",
      response: { kind: "linear", coefficient: -0.86 },
      inertiaTurns: 2,
      label: "retained households",
    },
    {
      id: "membership-decline-to-trust",
      source: "membership-decline",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.12 },
      inertiaTurns: 2,
      label: "shrinking base",
    },
    {
      id: "financial-strain-pressure",
      source: "_default_",
      target: "financial-strain",
      response: { kind: "constant", value: 0.7 },
      label: "fixed obligations",
    },
    {
      id: "stability-to-financial-strain",
      source: "financial-stability",
      target: "financial-strain",
      response: { kind: "linear", coefficient: -0.85 },
      inertiaTurns: 2,
      label: "solvent operations",
    },
    {
      id: "financial-strain-to-trust",
      source: "financial-strain",
      target: "leadership-trust",
      response: { kind: "linear", coefficient: -0.1 },
      inertiaTurns: 2,
      label: "financial anxiety",
    },
    {
      id: "reach-of-governance-to-lay",
      source: "governance-reach",
      target: "lay-leadership",
      response: { kind: "linear", coefficient: 0.18 },
      label: "coordinated service",
    },
    {
      id: "centralization-to-lay",
      source: "centralization",
      target: "lay-leadership",
      response: { kind: "linear", coefficient: -0.2 },
      inertiaTurns: 2,
      label: "local autonomy",
    },
    {
      id: "clergy-quality-to-mission",
      source: "clergy-quality",
      target: "mission-reach",
      response: { kind: "linear", coefficient: 0.2 },
      inertiaTurns: 3,
      label: "trained mission workers",
    },
    {
      id: "clergy-quality-to-participation",
      source: "clergy-quality",
      target: "worship-participation",
      response: { kind: "linear", coefficient: 0.15 },
      inertiaTurns: 3,
      label: "pastoral formation",
    },
  ],
} as const satisfies ScenarioDefinition;
