import type { EffectDefinition } from "../../simulation";

export const strasbourgEffects = [
  {
    id: "pastoral-training-to-teaching-quality",
    source: "pastoral-training",
    target: "teaching-quality",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 3,
    label: "Pastoral training affects teaching quality",
  },
  {
    id: "catechetical-instruction-to-teaching-quality",
    source: "catechetical-instruction",
    target: "teaching-quality",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Catechetical instruction affects teaching quality",
  },
  {
    id: "poor-relief-to-relief-reach",
    source: "poor-relief",
    target: "relief-reach",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 2,
    label: "Poor relief affects relief reach",
  },
  {
    id: "hospital-provision-to-relief-reach",
    source: "hospital-provision",
    target: "relief-reach",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 3,
    label: "Hospital provision affects relief reach",
  },
  {
    id: "council-oversight-to-civic-trust",
    source: "council-oversight",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: 0.24,
    },
    inertiaTurns: 2,
    label: "Council oversight affects civic trust",
  },
  {
    id: "administrative-reliability-to-civic-trust",
    source: "administrative-reliability",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Administrative reliability affects civic trust",
  },
  {
    id: "relief-reach-to-civic-trust",
    source: "relief-reach",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: 0.16,
    },
    inertiaTurns: 1,
    label: "Relief reach affects civic trust",
  },
  {
    id: "magistrat-satisfaction-to-civic-trust",
    source: "magistrat-satisfaction",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 1,
    label: "Magistrat satisfaction affects civic trust",
  },
  {
    id: "teaching-quality-to-church-unity",
    source: "teaching-quality",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Teaching quality affects church unity",
  },
  {
    id: "doctrinal-alignment-to-church-unity",
    source: "doctrinal-alignment",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.16,
    },
    inertiaTurns: 1,
    label: "Doctrinal alignment affects church unity",
  },
  {
    id: "worship-participation-to-church-unity",
    source: "worship-participation",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.14,
    },
    inertiaTurns: 1,
    label: "Worship participation affects church unity",
  },
  {
    id: "evangelicals-satisfaction-to-church-unity",
    source: "evangelicals-satisfaction",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.16,
    },
    inertiaTurns: 1,
    label: "Evangelicals satisfaction affects church unity",
  },
  {
    id: "traditionalists-satisfaction-to-church-unity",
    source: "traditionalists-satisfaction",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 1,
    label: "Traditionalists satisfaction affects church unity",
  },
  {
    id: "evangelical-diplomacy-to-external-security",
    source: "evangelical-diplomacy",
    target: "external-security",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 3,
    label: "Evangelical diplomacy affects external security",
  },
  {
    id: "sacramental-alignment-to-external-security",
    source: "sacramental-alignment",
    target: "external-security",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 3,
    label: "Sacramental alignment affects external security",
  },
  {
    id: "magistrat-satisfaction-to-external-security",
    source: "magistrat-satisfaction",
    target: "external-security",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 1,
    label: "Magistrat satisfaction affects external security",
  },
  {
    id: "schooling-to-literacy",
    source: "schooling",
    target: "literacy",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 4,
    label: "Schooling affects literacy",
  },
  {
    id: "print-circulation-to-literacy",
    source: "print-circulation",
    target: "literacy",
    response: {
      kind: "linear",
      coefficient: 0.16,
    },
    inertiaTurns: 2,
    label: "Print circulation affects literacy",
  },
  {
    id: "vernacular-printing-to-print-circulation",
    source: "vernacular-printing",
    target: "print-circulation",
    response: {
      kind: "linear",
      coefficient: 0.55,
    },
    inertiaTurns: 2,
    label: "Vernacular printing affects print circulation",
  },
  {
    id: "literacy-to-print-circulation",
    source: "literacy",
    target: "print-circulation",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 1,
    label: "Literacy affects print circulation",
  },
  {
    id: "pastoral-training-to-pastoral-coverage",
    source: "pastoral-training",
    target: "pastoral-coverage",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 3,
    label: "Pastoral training affects pastoral coverage",
  },
  {
    id: "parish-visitation-to-pastoral-coverage",
    source: "parish-visitation",
    target: "pastoral-coverage",
    response: {
      kind: "linear",
      coefficient: 0.22,
    },
    inertiaTurns: 2,
    label: "Parish visitation affects pastoral coverage",
  },
  {
    id: "rural-ministry-to-pastoral-coverage",
    source: "rural-ministry",
    target: "pastoral-coverage",
    response: {
      kind: "linear",
      coefficient: 0.14,
    },
    inertiaTurns: 3,
    label: "Rural ministry affects pastoral coverage",
  },
  {
    id: "financial-auditing-to-administrative-reliability",
    source: "financial-auditing",
    target: "administrative-reliability",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 2,
    label: "Financial auditing affects administrative reliability",
  },
  {
    id: "lay-eldership-to-administrative-reliability",
    source: "lay-eldership",
    target: "administrative-reliability",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 2,
    label: "Lay eldership affects administrative reliability",
  },
  {
    id: "council-oversight-to-administrative-reliability",
    source: "council-oversight",
    target: "administrative-reliability",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 1,
    label: "Council oversight affects administrative reliability",
  },
  {
    id: "relief-reach-to-household-hardship",
    source: "relief-reach",
    target: "household-hardship",
    response: {
      kind: "linear",
      coefficient: -0.4,
    },
    inertiaTurns: 1,
    label: "Relief reach affects household hardship",
  },
  {
    id: "provisioning-security-to-household-hardship",
    source: "provisioning-security",
    target: "household-hardship",
    response: {
      kind: "linear",
      coefficient: -0.22,
    },
    inertiaTurns: 1,
    label: "Provisioning security affects household hardship",
  },
  {
    id: "common-assessments-to-household-hardship",
    source: "common-assessments",
    target: "household-hardship",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 2,
    label: "Common assessments affects household hardship",
  },
  {
    id: "refugee-reception-to-refugee-integration",
    source: "refugee-reception",
    target: "refugee-integration",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 3,
    label: "Refugee reception affects refugee integration",
  },
  {
    id: "religious-forbearance-to-refugee-integration",
    source: "religious-forbearance",
    target: "refugee-integration",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects refugee integration",
  },
  {
    id: "relief-reach-to-refugee-integration",
    source: "relief-reach",
    target: "refugee-integration",
    response: {
      kind: "linear",
      coefficient: 0.14,
    },
    inertiaTurns: 1,
    label: "Relief reach affects refugee integration",
  },
  {
    id: "hospital-provision-to-hospital-capacity",
    source: "hospital-provision",
    target: "hospital-capacity",
    response: {
      kind: "linear",
      coefficient: 0.55,
    },
    inertiaTurns: 3,
    label: "Hospital provision affects hospital capacity",
  },
  {
    id: "charitable-confidence-to-hospital-capacity",
    source: "charitable-confidence",
    target: "hospital-capacity",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 1,
    label: "Charitable confidence affects hospital capacity",
  },
  {
    id: "grain-purchasing-to-provisioning-security",
    source: "grain-purchasing",
    target: "provisioning-security",
    response: {
      kind: "linear",
      coefficient: 0.42,
    },
    inertiaTurns: 2,
    label: "Grain purchasing affects provisioning security",
  },
  {
    id: "merchants-satisfaction-to-provisioning-security",
    source: "merchants-satisfaction",
    target: "provisioning-security",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Merchants satisfaction affects provisioning security",
  },
  {
    id: "catechetical-instruction-to-doctrinal-alignment",
    source: "catechetical-instruction",
    target: "doctrinal-alignment",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Catechetical instruction affects doctrinal alignment",
  },
  {
    id: "confessional-subscription-to-doctrinal-alignment",
    source: "confessional-subscription",
    target: "doctrinal-alignment",
    response: {
      kind: "linear",
      coefficient: 0.35,
    },
    inertiaTurns: 2,
    label: "Confessional subscription affects doctrinal alignment",
  },
  {
    id: "religious-forbearance-to-doctrinal-alignment",
    source: "religious-forbearance",
    target: "doctrinal-alignment",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects doctrinal alignment",
  },
  {
    id: "evangelical-diplomacy-to-diplomatic-obligations",
    source: "evangelical-diplomacy",
    target: "diplomatic-obligations",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 2,
    label: "Evangelical diplomacy affects diplomatic obligations",
  },
  {
    id: "sacramental-alignment-to-diplomatic-obligations",
    source: "sacramental-alignment",
    target: "diplomatic-obligations",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 2,
    label: "Sacramental alignment affects diplomatic obligations",
  },
  {
    id: "poor-relief-to-charitable-confidence",
    source: "poor-relief",
    target: "charitable-confidence",
    response: {
      kind: "linear",
      coefficient: 0.25,
    },
    inertiaTurns: 2,
    label: "Poor relief affects charitable confidence",
  },
  {
    id: "financial-auditing-to-charitable-confidence",
    source: "financial-auditing",
    target: "charitable-confidence",
    response: {
      kind: "linear",
      coefficient: 0.25,
    },
    inertiaTurns: 2,
    label: "Financial auditing affects charitable confidence",
  },
  {
    id: "hospital-capacity-to-charitable-confidence",
    source: "hospital-capacity",
    target: "charitable-confidence",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 1,
    label: "Hospital capacity affects charitable confidence",
  },
  {
    id: "congregational-singing-to-worship-participation",
    source: "congregational-singing",
    target: "worship-participation",
    response: {
      kind: "linear",
      coefficient: 0.35,
    },
    inertiaTurns: 2,
    label: "Congregational singing affects worship participation",
  },
  {
    id: "catechetical-instruction-to-worship-participation",
    source: "catechetical-instruction",
    target: "worship-participation",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 2,
    label: "Catechetical instruction affects worship participation",
  },
  {
    id: "parish-appointments-to-worship-participation",
    source: "parish-appointments",
    target: "worship-participation",
    response: {
      kind: "linear",
      coefficient: 0.12,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects worship participation",
  },
  {
    id: "council-oversight-to-pastoral-autonomy",
    source: "council-oversight",
    target: "pastoral-autonomy",
    response: {
      kind: "linear",
      coefficient: -0.35,
    },
    inertiaTurns: 1,
    label: "Council oversight affects pastoral autonomy",
  },
  {
    id: "parish-appointments-to-pastoral-autonomy",
    source: "parish-appointments",
    target: "pastoral-autonomy",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects pastoral autonomy",
  },
  {
    id: "confessional-subscription-to-pastoral-autonomy",
    source: "confessional-subscription",
    target: "pastoral-autonomy",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 1,
    label: "Confessional subscription affects pastoral autonomy",
  },
  {
    id: "rural-ministry-to-rural-connection",
    source: "rural-ministry",
    target: "rural-connection",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 3,
    label: "Rural ministry affects rural connection",
  },
  {
    id: "parish-appointments-to-rural-connection",
    source: "parish-appointments",
    target: "rural-connection",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects rural connection",
  },
  {
    id: "confessional-subscription-to-confessional-friction",
    source: "confessional-subscription",
    target: "confessional-friction",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 2,
    label: "Confessional subscription affects confessional friction",
  },
  {
    id: "devotional-images-to-confessional-friction",
    source: "devotional-images",
    target: "confessional-friction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Devotional images affects confessional friction",
  },
  {
    id: "religious-forbearance-to-confessional-friction",
    source: "religious-forbearance",
    target: "confessional-friction",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects confessional friction",
  },
  {
    id: "civic-trust-to-institutional-legitimacy",
    source: "civic-trust",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 1,
    label: "Civic trust affects institutional legitimacy",
  },
  {
    id: "church-unity-to-institutional-legitimacy",
    source: "church-unity",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Church unity affects institutional legitimacy",
  },
  {
    id: "rural-connection-to-institutional-legitimacy",
    source: "rural-connection",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 1,
    label: "Rural connection affects institutional legitimacy",
  },
  {
    id: "religious-forbearance-to-public-order",
    source: "religious-forbearance",
    target: "public-order",
    response: {
      kind: "linear",
      coefficient: 0.22,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects public order",
  },
  {
    id: "relief-reach-to-public-order",
    source: "relief-reach",
    target: "public-order",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Relief reach affects public order",
  },
  {
    id: "institutional-legitimacy-to-public-order",
    source: "institutional-legitimacy",
    target: "public-order",
    response: {
      kind: "linear",
      coefficient: 0.18,
    },
    inertiaTurns: 1,
    label: "Institutional legitimacy affects public order",
  },
  {
    id: "worship-reform-to-evangelicals-satisfaction",
    source: "worship-reform",
    target: "evangelicals-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.35,
    },
    inertiaTurns: 2,
    label: "Worship reform affects evangelicals satisfaction",
  },
  {
    id: "clerical-marriage-to-evangelicals-satisfaction",
    source: "clerical-marriage",
    target: "evangelicals-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 2,
    label: "Clerical marriage affects evangelicals satisfaction",
  },
  {
    id: "teaching-quality-to-evangelicals-satisfaction",
    source: "teaching-quality",
    target: "evangelicals-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Teaching quality affects evangelicals satisfaction",
  },
  {
    id: "religious-forbearance-to-evangelicals-satisfaction",
    source: "religious-forbearance",
    target: "evangelicals-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects evangelicals satisfaction",
  },
  {
    id: "worship-reform-to-traditionalists-satisfaction",
    source: "worship-reform",
    target: "traditionalists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.35,
    },
    inertiaTurns: 2,
    label: "Worship reform affects traditionalists satisfaction",
  },
  {
    id: "devotional-images-to-traditionalists-satisfaction",
    source: "devotional-images",
    target: "traditionalists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 2,
    label: "Devotional images affects traditionalists satisfaction",
  },
  {
    id: "religious-forbearance-to-traditionalists-satisfaction",
    source: "religious-forbearance",
    target: "traditionalists-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects traditionalists satisfaction",
  },
  {
    id: "clerical-marriage-to-traditionalists-satisfaction",
    source: "clerical-marriage",
    target: "traditionalists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 2,
    label: "Clerical marriage affects traditionalists satisfaction",
  },
  {
    id: "religious-forbearance-to-anabaptists-satisfaction",
    source: "religious-forbearance",
    target: "anabaptists-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.5,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects anabaptists satisfaction",
  },
  {
    id: "confessional-subscription-to-anabaptists-satisfaction",
    source: "confessional-subscription",
    target: "anabaptists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 2,
    label: "Confessional subscription affects anabaptists satisfaction",
  },
  {
    id: "lay-eldership-to-anabaptists-satisfaction",
    source: "lay-eldership",
    target: "anabaptists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 2,
    label: "Lay eldership affects anabaptists satisfaction",
  },
  {
    id: "religious-forbearance-to-spiritualists-satisfaction",
    source: "religious-forbearance",
    target: "spiritualists-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects spiritualists satisfaction",
  },
  {
    id: "confessional-subscription-to-spiritualists-satisfaction",
    source: "confessional-subscription",
    target: "spiritualists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 2,
    label: "Confessional subscription affects spiritualists satisfaction",
  },
  {
    id: "catechetical-instruction-to-spiritualists-satisfaction",
    source: "catechetical-instruction",
    target: "spiritualists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 2,
    label: "Catechetical instruction affects spiritualists satisfaction",
  },
  {
    id: "council-oversight-to-magistrat-satisfaction",
    source: "council-oversight",
    target: "magistrat-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 2,
    label: "Council oversight affects magistrat satisfaction",
  },
  {
    id: "administrative-reliability-to-magistrat-satisfaction",
    source: "administrative-reliability",
    target: "magistrat-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.25,
    },
    inertiaTurns: 1,
    label: "Administrative reliability affects magistrat satisfaction",
  },
  {
    id: "parish-appointments-to-magistrat-satisfaction",
    source: "parish-appointments",
    target: "magistrat-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects magistrat satisfaction",
  },
  {
    id: "endowment-allocation-to-cathedral-chapter-satisfaction",
    source: "endowment-allocation",
    target: "cathedral-chapter-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.35,
    },
    inertiaTurns: 2,
    label: "Endowment allocation affects cathedral chapter satisfaction",
  },
  {
    id: "worship-reform-to-cathedral-chapter-satisfaction",
    source: "worship-reform",
    target: "cathedral-chapter-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 2,
    label: "Worship reform affects cathedral chapter satisfaction",
  },
  {
    id: "religious-forbearance-to-cathedral-chapter-satisfaction",
    source: "religious-forbearance",
    target: "cathedral-chapter-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects cathedral chapter satisfaction",
  },
  {
    id: "pastoral-training-to-pastors-satisfaction",
    source: "pastoral-training",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 3,
    label: "Pastoral training affects pastors satisfaction",
  },
  {
    id: "pastoral-autonomy-to-pastors-satisfaction",
    source: "pastoral-autonomy",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 1,
    label: "Pastoral autonomy affects pastors satisfaction",
  },
  {
    id: "clerical-marriage-to-pastors-satisfaction",
    source: "clerical-marriage",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 2,
    label: "Clerical marriage affects pastors satisfaction",
  },
  {
    id: "rural-ministry-to-pastors-satisfaction",
    source: "rural-ministry",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 2,
    label: "Rural ministry affects pastors satisfaction",
  },
  {
    id: "relief-reach-to-guilds-satisfaction",
    source: "relief-reach",
    target: "guilds-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 1,
    label: "Relief reach affects guilds satisfaction",
  },
  {
    id: "public-order-to-guilds-satisfaction",
    source: "public-order",
    target: "guilds-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Public order affects guilds satisfaction",
  },
  {
    id: "common-assessments-to-guilds-satisfaction",
    source: "common-assessments",
    target: "guilds-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 2,
    label: "Common assessments affects guilds satisfaction",
  },
  {
    id: "external-security-to-merchants-satisfaction",
    source: "external-security",
    target: "merchants-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.25,
    },
    inertiaTurns: 1,
    label: "External security affects merchants satisfaction",
  },
  {
    id: "public-order-to-merchants-satisfaction",
    source: "public-order",
    target: "merchants-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Public order affects merchants satisfaction",
  },
  {
    id: "common-assessments-to-merchants-satisfaction",
    source: "common-assessments",
    target: "merchants-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 2,
    label: "Common assessments affects merchants satisfaction",
  },
  {
    id: "grain-purchasing-to-merchants-satisfaction",
    source: "grain-purchasing",
    target: "merchants-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 2,
    label: "Grain purchasing affects merchants satisfaction",
  },
  {
    id: "refugee-integration-to-french-refugees-satisfaction",
    source: "refugee-integration",
    target: "french-refugees-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 1,
    label: "Refugee integration affects french refugees satisfaction",
  },
  {
    id: "religious-forbearance-to-french-refugees-satisfaction",
    source: "religious-forbearance",
    target: "french-refugees-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects french refugees satisfaction",
  },
  {
    id: "confessional-subscription-to-french-refugees-satisfaction",
    source: "confessional-subscription",
    target: "french-refugees-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 2,
    label: "Confessional subscription affects french refugees satisfaction",
  },
  {
    id: "endowment-allocation-to-dominican-convents-satisfaction",
    source: "endowment-allocation",
    target: "dominican-convents-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 2,
    label: "Endowment allocation affects dominican convents satisfaction",
  },
  {
    id: "parish-visitation-to-dominican-convents-satisfaction",
    source: "parish-visitation",
    target: "dominican-convents-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 2,
    label: "Parish visitation affects dominican convents satisfaction",
  },
  {
    id: "religious-forbearance-to-dominican-convents-satisfaction",
    source: "religious-forbearance",
    target: "dominican-convents-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Religious forbearance affects dominican convents satisfaction",
  },
  {
    id: "rural-connection-to-rural-parishes-satisfaction",
    source: "rural-connection",
    target: "rural-parishes-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.45,
    },
    inertiaTurns: 1,
    label: "Rural connection affects rural parishes satisfaction",
  },
  {
    id: "parish-appointments-to-rural-parishes-satisfaction",
    source: "parish-appointments",
    target: "rural-parishes-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects rural parishes satisfaction",
  },
  {
    id: "common-assessments-to-rural-parishes-satisfaction",
    source: "common-assessments",
    target: "rural-parishes-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.18,
    },
    inertiaTurns: 2,
    label: "Common assessments affects rural parishes satisfaction",
  },
  {
    id: "worship-reform-to-evangelicals-membership",
    source: "worship-reform",
    target: "evangelicals-membership",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 4,
    label: "Worship reform affects evangelicals membership",
  },
  {
    id: "worship-participation-to-evangelicals-membership",
    source: "worship-participation",
    target: "evangelicals-membership",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 4,
    label: "Worship participation affects evangelicals membership",
  },
  {
    id: "worship-reform-to-traditionalists-membership",
    source: "worship-reform",
    target: "traditionalists-membership",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 4,
    label: "Worship reform affects traditionalists membership",
  },
  {
    id: "religious-forbearance-to-traditionalists-membership",
    source: "religious-forbearance",
    target: "traditionalists-membership",
    response: {
      kind: "linear",
      coefficient: 0.04,
    },
    inertiaTurns: 4,
    label: "Religious forbearance affects traditionalists membership",
  },
  {
    id: "religious-forbearance-to-anabaptists-membership",
    source: "religious-forbearance",
    target: "anabaptists-membership",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 4,
    label: "Religious forbearance affects anabaptists membership",
  },
  {
    id: "confessional-subscription-to-anabaptists-membership",
    source: "confessional-subscription",
    target: "anabaptists-membership",
    response: {
      kind: "linear",
      coefficient: -0.03,
    },
    inertiaTurns: 4,
    label: "Confessional subscription affects anabaptists membership",
  },
  {
    id: "religious-forbearance-to-spiritualists-membership",
    source: "religious-forbearance",
    target: "spiritualists-membership",
    response: {
      kind: "linear",
      coefficient: 0.06,
    },
    inertiaTurns: 4,
    label: "Religious forbearance affects spiritualists membership",
  },
  {
    id: "confessional-subscription-to-spiritualists-membership",
    source: "confessional-subscription",
    target: "spiritualists-membership",
    response: {
      kind: "linear",
      coefficient: -0.025,
    },
    inertiaTurns: 4,
    label: "Confessional subscription affects spiritualists membership",
  },
  {
    id: "refugee-reception-to-french-refugees-membership",
    source: "refugee-reception",
    target: "french-refugees-membership",
    response: {
      kind: "linear",
      coefficient: 0.07,
    },
    inertiaTurns: 4,
    label: "Refugee reception affects french refugees membership",
  },
  {
    id: "refugee-integration-to-french-refugees-membership",
    source: "refugee-integration",
    target: "french-refugees-membership",
    response: {
      kind: "linear",
      coefficient: 0.03,
    },
    inertiaTurns: 4,
    label: "Refugee integration affects french refugees membership",
  },
  {
    id: "council-oversight-to-magistrat-membership",
    source: "council-oversight",
    target: "magistrat-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Council oversight affects magistrat membership",
  },
  {
    id: "religious-forbearance-to-cathedral-chapter-membership",
    source: "religious-forbearance",
    target: "cathedral-chapter-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Religious forbearance affects cathedral chapter membership",
  },
  {
    id: "pastoral-coverage-to-pastors-membership",
    source: "pastoral-coverage",
    target: "pastors-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Pastoral coverage affects pastors membership",
  },
  {
    id: "provisioning-security-to-guilds-membership",
    source: "provisioning-security",
    target: "guilds-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Provisioning security affects guilds membership",
  },
  {
    id: "external-security-to-merchants-membership",
    source: "external-security",
    target: "merchants-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "External security affects merchants membership",
  },
  {
    id: "religious-forbearance-to-dominican-convents-membership",
    source: "religious-forbearance",
    target: "dominican-convents-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Religious forbearance affects dominican convents membership",
  },
  {
    id: "rural-connection-to-rural-parishes-membership",
    source: "rural-connection",
    target: "rural-parishes-membership",
    response: {
      kind: "linear",
      coefficient: 0.05,
    },
    inertiaTurns: 4,
    label: "Rural connection affects rural parishes membership",
  },
  {
    id: "worship-reform-to-street-unrest",
    source: "worship-reform",
    target: "street-unrest",
    response: {
      kind: "linear",
      coefficient: 0.3,
    },
    inertiaTurns: 1,
    label: "Worship reform affects street unrest",
  },
  {
    id: "devotional-images-to-street-unrest",
    source: "devotional-images",
    target: "street-unrest",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Devotional images affects street unrest",
  },
  {
    id: "religious-forbearance-to-street-unrest",
    source: "religious-forbearance",
    target: "street-unrest",
    response: {
      kind: "linear",
      coefficient: -0.4,
    },
    inertiaTurns: 1,
    label: "Religious forbearance affects street unrest",
  },
  {
    id: "relief-reach-to-street-unrest",
    source: "relief-reach",
    target: "street-unrest",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 1,
    label: "Relief reach affects street unrest",
  },
  {
    id: "worship-reform-to-imperial-exposure",
    source: "worship-reform",
    target: "imperial-exposure",
    response: {
      kind: "linear",
      coefficient: 0.25,
    },
    inertiaTurns: 1,
    label: "Worship reform affects imperial exposure",
  },
  {
    id: "evangelical-diplomacy-to-imperial-exposure",
    source: "evangelical-diplomacy",
    target: "imperial-exposure",
    response: {
      kind: "linear",
      coefficient: -0.55,
    },
    inertiaTurns: 2,
    label: "Evangelical diplomacy affects imperial exposure",
  },
  {
    id: "council-oversight-to-imperial-exposure",
    source: "council-oversight",
    target: "imperial-exposure",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 1,
    label: "Council oversight affects imperial exposure",
  },
  {
    id: "household-hardship-to-relief-strain",
    source: "household-hardship",
    target: "relief-strain",
    response: {
      kind: "linear",
      coefficient: 0.2,
    },
    inertiaTurns: 1,
    label: "Household hardship affects relief strain",
  },
  {
    id: "poor-relief-to-relief-strain",
    source: "poor-relief",
    target: "relief-strain",
    response: {
      kind: "linear",
      coefficient: -0.6,
    },
    inertiaTurns: 2,
    label: "Poor relief affects relief strain",
  },
  {
    id: "hospital-capacity-to-relief-strain",
    source: "hospital-capacity",
    target: "relief-strain",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 1,
    label: "Hospital capacity affects relief strain",
  },
  {
    id: "household-hardship-to-provisioning-crisis",
    source: "household-hardship",
    target: "provisioning-crisis",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 1,
    label: "Household hardship affects provisioning crisis",
  },
  {
    id: "provisioning-security-to-provisioning-crisis",
    source: "provisioning-security",
    target: "provisioning-crisis",
    response: {
      kind: "linear",
      coefficient: -0.6,
    },
    inertiaTurns: 1,
    label: "Provisioning security affects provisioning crisis",
  },
  {
    id: "hospital-capacity-to-provisioning-crisis",
    source: "hospital-capacity",
    target: "provisioning-crisis",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 1,
    label: "Hospital capacity affects provisioning crisis",
  },
  {
    id: "pastoral-coverage-to-pastoral-shortage",
    source: "pastoral-coverage",
    target: "pastoral-shortage",
    response: {
      kind: "linear",
      coefficient: -0.6,
    },
    inertiaTurns: 1,
    label: "Pastoral coverage affects pastoral shortage",
  },
  {
    id: "teaching-quality-to-pastoral-shortage",
    source: "teaching-quality",
    target: "pastoral-shortage",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 1,
    label: "Teaching quality affects pastoral shortage",
  },
  {
    id: "confessional-friction-to-confessional-polarization",
    source: "confessional-friction",
    target: "confessional-polarization",
    response: {
      kind: "linear",
      coefficient: 0.65,
    },
    inertiaTurns: 1,
    label: "Confessional friction affects confessional polarization",
  },
  {
    id: "public-order-to-confessional-polarization",
    source: "public-order",
    target: "confessional-polarization",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 1,
    label: "Public order affects confessional polarization",
  },
  {
    id: "literacy-to-flourishing-schools",
    source: "literacy",
    target: "flourishing-schools",
    response: {
      kind: "linear",
      coefficient: 0.6,
    },
    inertiaTurns: 1,
    label: "Literacy affects flourishing schools",
  },
  {
    id: "teaching-quality-to-flourishing-schools",
    source: "teaching-quality",
    target: "flourishing-schools",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 1,
    label: "Teaching quality affects flourishing schools",
  },
  {
    id: "charitable-confidence-to-trusted-common-provision",
    source: "charitable-confidence",
    target: "trusted-common-provision",
    response: {
      kind: "linear",
      coefficient: 0.6,
    },
    inertiaTurns: 1,
    label: "Charitable confidence affects trusted common provision",
  },
  {
    id: "relief-reach-to-trusted-common-provision",
    source: "relief-reach",
    target: "trusted-common-provision",
    response: {
      kind: "linear",
      coefficient: 0.4,
    },
    inertiaTurns: 1,
    label: "Relief reach affects trusted common provision",
  },
  {
    id: "devotional-images-to-image-controversy",
    source: "devotional-images",
    target: "image-controversy",
    response: {
      kind: "linear",
      coefficient: 0.65,
    },
    inertiaTurns: 1,
    label: "Devotional images affects image controversy",
  },
  {
    id: "religious-forbearance-to-image-controversy",
    source: "religious-forbearance",
    target: "image-controversy",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 1,
    label: "Religious forbearance affects image controversy",
  },
  {
    id: "parish-visitation-to-image-controversy",
    source: "parish-visitation",
    target: "image-controversy",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 2,
    label: "Parish visitation affects image controversy",
  },
  {
    id: "refugee-reception-to-refugee-strain",
    source: "refugee-reception",
    target: "refugee-strain",
    response: {
      kind: "linear",
      coefficient: 0.55,
    },
    inertiaTurns: 1,
    label: "Refugee reception affects refugee strain",
  },
  {
    id: "refugee-integration-to-refugee-strain",
    source: "refugee-integration",
    target: "refugee-strain",
    response: {
      kind: "linear",
      coefficient: -0.4,
    },
    inertiaTurns: 1,
    label: "Refugee integration affects refugee strain",
  },
  {
    id: "relief-reach-to-refugee-strain",
    source: "relief-reach",
    target: "refugee-strain",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 1,
    label: "Relief reach affects refugee strain",
  },
  {
    id: "print-circulation-to-printing-controversy",
    source: "print-circulation",
    target: "printing-controversy",
    response: {
      kind: "linear",
      coefficient: 0.7,
    },
    inertiaTurns: 1,
    label: "Print circulation affects printing controversy",
  },
  {
    id: "teaching-quality-to-printing-controversy",
    source: "teaching-quality",
    target: "printing-controversy",
    response: {
      kind: "linear",
      coefficient: -0.3,
    },
    inertiaTurns: 1,
    label: "Teaching quality affects printing controversy",
  },
  {
    id: "doctrinal-alignment-to-printing-controversy",
    source: "doctrinal-alignment",
    target: "printing-controversy",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 1,
    label: "Doctrinal alignment affects printing controversy",
  },
  {
    id: "rural-connection-to-rural-estrangement",
    source: "rural-connection",
    target: "rural-estrangement",
    response: {
      kind: "linear",
      coefficient: -0.55,
    },
    inertiaTurns: 1,
    label: "Rural connection affects rural estrangement",
  },
  {
    id: "parish-appointments-to-rural-estrangement",
    source: "parish-appointments",
    target: "rural-estrangement",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 2,
    label: "Parish appointments affects rural estrangement",
  },
  {
    id: "street-unrest-to-civic-trust",
    source: "street-unrest",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: -0.28,
    },
    inertiaTurns: 1,
    label: "Street unrest affects civic trust",
  },
  {
    id: "street-unrest-to-public-order",
    source: "street-unrest",
    target: "public-order",
    response: {
      kind: "linear",
      coefficient: -0.2,
    },
    inertiaTurns: 1,
    label: "Street unrest affects public order",
  },
  {
    id: "imperial-exposure-to-external-security",
    source: "imperial-exposure",
    target: "external-security",
    response: {
      kind: "linear",
      coefficient: -0.18,
    },
    inertiaTurns: 1,
    label: "Imperial exposure affects external security",
  },
  {
    id: "imperial-exposure-to-money",
    source: "imperial-exposure",
    target: "money",
    response: {
      kind: "linear",
      coefficient: -2,
    },
    inertiaTurns: 1,
    label: "Imperial exposure affects money",
  },
  {
    id: "relief-strain-to-civic-trust",
    source: "relief-strain",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Relief strain affects civic trust",
  },
  {
    id: "relief-strain-to-money",
    source: "relief-strain",
    target: "money",
    response: {
      kind: "linear",
      coefficient: -1.5,
    },
    inertiaTurns: 1,
    label: "Relief strain affects money",
  },
  {
    id: "provisioning-crisis-to-household-hardship",
    source: "provisioning-crisis",
    target: "household-hardship",
    response: {
      kind: "linear",
      coefficient: 0.15,
    },
    inertiaTurns: 1,
    label: "Provisioning crisis affects household hardship",
  },
  {
    id: "provisioning-crisis-to-merchants-satisfaction",
    source: "provisioning-crisis",
    target: "merchants-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Provisioning crisis affects merchants satisfaction",
  },
  {
    id: "pastoral-shortage-to-church-unity",
    source: "pastoral-shortage",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 1,
    label: "Pastoral shortage affects church unity",
  },
  {
    id: "pastoral-shortage-to-pastors-satisfaction",
    source: "pastoral-shortage",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Pastoral shortage affects pastors satisfaction",
  },
  {
    id: "confessional-polarization-to-church-unity",
    source: "confessional-polarization",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: -0.25,
    },
    inertiaTurns: 1,
    label: "Confessional polarization affects church unity",
  },
  {
    id: "confessional-polarization-to-civic-trust",
    source: "confessional-polarization",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Confessional polarization affects civic trust",
  },
  {
    id: "flourishing-schools-to-institutional-legitimacy",
    source: "flourishing-schools",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.06,
    },
    inertiaTurns: 1,
    label: "Flourishing schools affects institutional legitimacy",
  },
  {
    id: "flourishing-schools-to-pastors-satisfaction",
    source: "flourishing-schools",
    target: "pastors-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.06,
    },
    inertiaTurns: 1,
    label: "Flourishing schools affects pastors satisfaction",
  },
  {
    id: "trusted-common-provision-to-civic-trust",
    source: "trusted-common-provision",
    target: "civic-trust",
    response: {
      kind: "linear",
      coefficient: 0.06,
    },
    inertiaTurns: 1,
    label: "Trusted common provision affects civic trust",
  },
  {
    id: "trusted-common-provision-to-guilds-satisfaction",
    source: "trusted-common-provision",
    target: "guilds-satisfaction",
    response: {
      kind: "linear",
      coefficient: 0.06,
    },
    inertiaTurns: 1,
    label: "Trusted common provision affects guilds satisfaction",
  },
  {
    id: "image-controversy-to-traditionalists-satisfaction",
    source: "image-controversy",
    target: "traditionalists-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Image controversy affects traditionalists satisfaction",
  },
  {
    id: "image-controversy-to-church-unity",
    source: "image-controversy",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 1,
    label: "Image controversy affects church unity",
  },
  {
    id: "refugee-strain-to-guilds-satisfaction",
    source: "refugee-strain",
    target: "guilds-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.12,
    },
    inertiaTurns: 1,
    label: "Refugee strain affects guilds satisfaction",
  },
  {
    id: "refugee-strain-to-money",
    source: "refugee-strain",
    target: "money",
    response: {
      kind: "linear",
      coefficient: -1.5,
    },
    inertiaTurns: 1,
    label: "Refugee strain affects money",
  },
  {
    id: "printing-controversy-to-doctrinal-alignment",
    source: "printing-controversy",
    target: "doctrinal-alignment",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 1,
    label: "Printing controversy affects doctrinal alignment",
  },
  {
    id: "printing-controversy-to-magistrat-satisfaction",
    source: "printing-controversy",
    target: "magistrat-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 1,
    label: "Printing controversy affects magistrat satisfaction",
  },
  {
    id: "rural-estrangement-to-rural-parishes-satisfaction",
    source: "rural-estrangement",
    target: "rural-parishes-satisfaction",
    response: {
      kind: "linear",
      coefficient: -0.15,
    },
    inertiaTurns: 1,
    label: "Rural estrangement affects rural parishes satisfaction",
  },
  {
    id: "rural-estrangement-to-church-unity",
    source: "rural-estrangement",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: -0.1,
    },
    inertiaTurns: 1,
    label: "Rural estrangement affects church unity",
  },
  {
    id: "common-assessments-to-revenue",
    source: "common-assessments",
    target: "revenue",
    response: {
      kind: "linear",
      coefficient: 8,
    },
    inertiaTurns: 1,
    label: "Common assessments affects revenue",
  },
  {
    id: "endowment-allocation-to-revenue",
    source: "endowment-allocation",
    target: "revenue",
    response: {
      kind: "linear",
      coefficient: 5,
    },
    inertiaTurns: 1,
    label: "Endowment allocation affects revenue",
  },
  {
    id: "merchants-satisfaction-to-revenue",
    source: "merchants-satisfaction",
    target: "revenue",
    response: {
      kind: "linear",
      coefficient: 4,
    },
    inertiaTurns: 1,
    label: "Merchants satisfaction affects revenue",
  },
  {
    id: "charitable-confidence-to-revenue",
    source: "charitable-confidence",
    target: "revenue",
    response: {
      kind: "linear",
      coefficient: 3,
    },
    inertiaTurns: 1,
    label: "Charitable confidence affects revenue",
  },
  {
    id: "cathedral-chapter-satisfaction-to-external-security",
    source: "cathedral-chapter-satisfaction",
    target: "external-security",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 1,
    label: "Cathedral chapter satisfaction affects external security",
  },
  {
    id: "dominican-convents-satisfaction-to-institutional-legitimacy",
    source: "dominican-convents-satisfaction",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 1,
    label: "Dominican convents satisfaction affects institutional legitimacy",
  },
  {
    id: "spiritualists-satisfaction-to-church-unity",
    source: "spiritualists-satisfaction",
    target: "church-unity",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 1,
    label: "Spiritualists satisfaction affects church unity",
  },
  {
    id: "anabaptists-satisfaction-to-public-order",
    source: "anabaptists-satisfaction",
    target: "public-order",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 1,
    label: "Anabaptists satisfaction affects public order",
  },
  {
    id: "pastors-satisfaction-to-pastoral-coverage",
    source: "pastors-satisfaction",
    target: "pastoral-coverage",
    response: {
      kind: "linear",
      coefficient: 0.1,
    },
    inertiaTurns: 1,
    label: "Pastors satisfaction affects pastoral coverage",
  },
  {
    id: "rural-parishes-satisfaction-to-rural-connection",
    source: "rural-parishes-satisfaction",
    target: "rural-connection",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 1,
    label: "Rural parishes satisfaction affects rural connection",
  },
  {
    id: "french-refugees-satisfaction-to-institutional-legitimacy",
    source: "french-refugees-satisfaction",
    target: "institutional-legitimacy",
    response: {
      kind: "linear",
      coefficient: 0.08,
    },
    inertiaTurns: 1,
    label: "French refugees satisfaction affects institutional legitimacy",
  },
  {
    id: "guilds-membership-to-revenue",
    source: "guilds-membership",
    target: "revenue",
    response: {
      kind: "linear",
      coefficient: 1,
    },
    inertiaTurns: 1,
    label: "Guilds membership affects revenue",
  },
  {
    id: "french-refugees-membership-to-expenditure",
    source: "french-refugees-membership",
    target: "expenditure",
    response: {
      kind: "linear",
      coefficient: 2,
    },
    inertiaTurns: 2,
    label: "French refugees membership affects expenditure",
  },
  {
    id: "revenue-to-money",
    source: "revenue",
    target: "money",
    response: {
      kind: "linear",
      coefficient: 1,
    },
    inertiaTurns: 1,
    label: "Revenue affects money",
  },
  {
    id: "expenditure-to-money",
    source: "expenditure",
    target: "money",
    response: {
      kind: "linear",
      coefficient: -1,
    },
    inertiaTurns: 1,
    label: "Expenditure affects money",
  },
  {
    id: "civic-trust-to-authority",
    source: "civic-trust",
    target: "authority",
    response: {
      kind: "linear",
      coefficient: 3,
    },
    inertiaTurns: 1,
    label: "Civic trust affects authority",
  },
  {
    id: "institutional-legitimacy-to-authority",
    source: "institutional-legitimacy",
    target: "authority",
    response: {
      kind: "linear",
      coefficient: 2,
    },
    inertiaTurns: 1,
    label: "Institutional legitimacy affects authority",
  },
  {
    id: "council-oversight-to-authority",
    source: "council-oversight",
    target: "authority",
    response: {
      kind: "linear",
      coefficient: -2,
    },
    inertiaTurns: 1,
    label: "Council oversight affects authority",
  },
  {
    id: "religious-forbearance-to-authority",
    source: "religious-forbearance",
    target: "authority",
    response: {
      kind: "linear",
      coefficient: -1.5,
    },
    inertiaTurns: 1,
    label: "Religious forbearance affects authority",
  },
  {
    id: "poor-relief-to-expenditure",
    source: "poor-relief",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 4,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "refugee-reception-to-expenditure",
    source: "refugee-reception",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 3,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "hospital-provision-to-expenditure",
    source: "hospital-provision",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 3,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "grain-purchasing-to-expenditure",
    source: "grain-purchasing",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 2,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "pastoral-training-to-expenditure",
    source: "pastoral-training",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 3,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "schooling-to-expenditure",
    source: "schooling",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 3,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "vernacular-printing-to-expenditure",
    source: "vernacular-printing",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 1.5,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "evangelical-diplomacy-to-expenditure",
    source: "evangelical-diplomacy",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 2,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "parish-visitation-to-expenditure",
    source: "parish-visitation",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 1.5,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "lay-eldership-to-expenditure",
    source: "lay-eldership",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 1,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "congregational-singing-to-expenditure",
    source: "congregational-singing",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 0.8,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "catechetical-instruction-to-expenditure",
    source: "catechetical-instruction",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 1,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "financial-auditing-to-expenditure",
    source: "financial-auditing",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 1,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "rural-ministry-to-expenditure",
    source: "rural-ministry",
    target: "expenditure",
    response: {
      kind: "power",
      coefficient: 2,
      exponent: 1.5,
    },
    inertiaTurns: 1,
    label: "Continuing provision with rising marginal cost",
  },
  {
    id: "diplomatic-obligations-to-expenditure",
    source: "diplomatic-obligations",
    target: "expenditure",
    response: {
      kind: "linear",
      coefficient: 2,
    },
    inertiaTurns: 1,
    label: "Diplomatic obligations affects expenditure",
  },
  {
    id: "ordinary-authority",
    source: "_default_",
    target: "authority",
    response: {
      kind: "constant",
      value: 1.5,
    },
    label: "Ordinary annual provision",
  },
] satisfies readonly EffectDefinition[];
